CREATE DATABASE IF NOT EXISTS emr_system;
USE emr_system;

CREATE TABLE PATIENTS (
    INTERNALID INT,
    RECORDSTATUS VARCHAR(255),
    EXTERNALID INT,
    IHI VARCHAR(50),
    IHISTATUS VARCHAR(255),
    IHIRECORDSTATUS VARCHAR(255),
    IHISOURCE VARCHAR(255),
    ORIGIN VARCHAR(255),
    PATIENTSTATUS VARCHAR(255),
    DATEOFDEATH DATE,
    TITLECODE VARCHAR(10),
    FIRSTNAME VARCHAR(255),
    MIDDLENAME VARCHAR(255),
    SURNAME VARCHAR(255),
    PREFERREDNAME VARCHAR(255),
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    CITY VARCHAR(255),
    POSTCODE VARCHAR(20),
    POSTALADDRESS VARCHAR(255),
    POSTALCITY VARCHAR(255),
    POSTALPOSTCODE VARCHAR(20),
    DOB DATE,
    SEXCODE VARCHAR(10),
    ETHNICCODE VARCHAR(10),
    HOMEPHONE VARCHAR(20),
    WORKPHONE VARCHAR(20),
    MOBILEPHONE VARCHAR(20),
    MEDICARENO VARCHAR(20),
    MEDICARELINENO VARCHAR(20),
    MEDICAREEXPIRY DATE,
    PENSIONCODE VARCHAR(10),
    PENSIONNO VARCHAR(20),
    PENSIONSTART DATE,
    PENSIONEXPIRY DATE,
    DVACODE VARCHAR(10),
    DVANO VARCHAR(20),
    SAFETYNETNO VARCHAR(20),
    RECORDNO VARCHAR(50),
    RELIGION VARCHAR(255),
    HEALTHFUNDNO VARCHAR(20),
    HEALTHFUNDNAME VARCHAR(255),
    HEALTHFUNDID VARCHAR(50),
    HEALTHFUNDEXPIRY DATE,
    ACCOUNTCODE VARCHAR(50),
    USERID INT,
    DENYACCESS BOOLEAN,
    NOREMINDERS BOOLEAN,
    CONTACTMETHOD VARCHAR(255),
    HEADOFFAMILYID INT,
    NEXTOFKINID INT,
    EMERGENCYID INT,
    REFERRINGDOCTOR VARCHAR(255),
    REFERRALDATE DATE,
    REFERRALCODE VARCHAR(50),
    ERX BOOLEAN,
    DISPENSE BOOLEAN,
    MEDVIEW BOOLEAN,
    PHARMACYID INT,
    CTG BOOLEAN,
    OTHERNOTES TEXT,
    CONSENTSMSREMINDER BOOLEAN,
    CREATED DATETIME,
    CREATEDBY VARCHAR(255),
    UPDATED DATETIME,
    UPDATEDBY VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCOUNTRY VARCHAR(255),
    IHIVALIDATED BOOLEAN,
    DEFAULTVISITTYPE VARCHAR(255),
    PREVIOUSUSERID INT,
    REGISTRATIONID INT,
    ENROLMENTID INT,
    QED BOOLEAN,
  ELIGIBLE_PUBLIC_FUNDING BOOLEAN,
    ENROLMENTCHECK BOOLEAN,
    HCHTIER VARCHAR(10),
    HCHSTARTED DATE,
    HCHCURRENT DATE,
    PENDINGMOBILECHANGE VARCHAR(20),
    GenderCode VARCHAR(10),
    PronounCode VARCHAR(10),
    DifferentIdentity BOOLEAN,
    ExtractionOptOut BOOLEAN,
    eScriptDefault BOOLEAN,
    eScriptToken TEXT,
    AtRiskOfCOVID BOOLEAN,
    VPE VARCHAR(255),
    IHIValidation BOOLEAN,
    MCOLverifydate DATE,
    UseMBAddress BOOLEAN,
    PublicFunding BOOLEAN,
    FinDependant VARCHAR(255),
    CSCHolder BOOLEAN,
    HUCHolder BOOLEAN,
    CSCNumber VARCHAR(20),
    IncSuppNumber VARCHAR(20),
    HUCNumber VARCHAR(20),
    CSCValid BOOLEAN,
    CSCExpiry DATE,
    HUCValid BOOLEAN,
    HUCExpiry DATE,
    IWI VARCHAR(255),
 OVERALL_PATIENTVERSION INT,
    CORE_VERSION INT,
    MOH_CHECKED BOOLEAN,
    COUNTRYOFBIRTH VARCHAR(255),
    COUNTRYOFBIRTH_SOURCE VARCHAR(255),
    PLACEOFBIRTH VARCHAR(255),
    CITIZEN BOOLEAN,
    CITIZEN_SOURCE VARCHAR(255),
    DATEOFDEATHSOURCE VARCHAR(255),
    NAME_SOURCE VARCHAR(255),
    NAME_SETID INT,
    NAME_VERSION INT,
    NAME_TYPE VARCHAR(50),
    ADDRESS_GEOTAG TEXT,
    ADDRESS_SETID INT,
    ADDRESS_VERSION INT,
    ADDRESS_DOMICILE VARCHAR(255),
    ADDRESS_NOTVALID_REASON TEXT,
    ESAM_CHECKED BOOLEAN,
    POSTAL_SUBURB VARCHAR(255),
    POSTAL_ADDRESS_GEOTAG TEXT,
    POSTAL_ADDRESS_DOMICILE VARCHAR(255),
    POSTAL_ADDRESS_NOTVALID_REASON TEXT,
    POSTAL_ESAM_CHECKED BOOLEAN,
    DOB_SOURCE VARCHAR(255),
    ETHNIC1CODE VARCHAR(10),
    ETHNIC2CODE VARCHAR(10),
    PRIMARY KEY (INTERNALID)
);country_table

INSERT INTO PATIENTS (
    INTERNALID, 
    RECORDSTATUS, 
    EXTERNALID,
    IHI, 
    IHISTATUS, 
    IHIRECORDSTATUS, 
    IHISOURCE, 
    ORIGIN, 
    PATIENTSTATUS, 
    DATEOFDEATH, 
    TITLECODE, 
    FIRSTNAME, 
    MIDDLENAME, 
    SURNAME, 
    PREFERREDNAME, 
    ADDRESS1, 
    ADDRESS2, 
    CITY, 
    POSTCODE, 
    POSTALADDRESS, 
    POSTALCITY, 
    POSTALPOSTCODE, 
    DOB, 
    SEXCODE, 
    ETHNICCODE, 
    HOMEPHONE, 
    WORKPHONE, 
    MOBILEPHONE, 
    MEDICARENO, 
    MEDICARELINENO, 
    MEDICAREEXPIRY, 
    PENSIONCODE, 
    PENSIONNO, 
    PENSIONSTART, 
    PENSIONEXPIRY, 
    DVACODE, 
    DVANO, 
    SAFETYNETNO, 
    RECORDNO, 
    RELIGION, 
    HEALTHFUNDNO, 
    HEALTHFUNDNAME, 
    HEALTHFUNDID, 
    HEALTHFUNDEXPIRY, 
    ACCOUNTCODE, 
    USERID, 
    DENYACCESS, 
    NOREMINDERS, 
    CONTACTMETHOD, 
    HEADOFFAMILYID,
    NEXTOFKINID,
    EMERGENCYID,
    REFERRINGDOCTOR,
    REFERRALDATE,
    REFERRALCODE,
    ERX,
    DISPENSE, 
    MEDVIEW,
    PHARMACYID,
    CTG,
    OTHERNOTES,
    CONSENTSMSREMINDER, 
    CREATED,
    CREATEDBY,
    UPDATED, 
    UPDATEDBY,
    COUNTRY, 
    POSTALCOUNTRY,
    IHIVALIDATED,
    DEFAULTVISITTYPE,
    PREVIOUSUSERID,
    REGISTRATIONID,
    ENROLMENTID,
    QED, 
    ELIGIBLE_PUBLIC_FUNDING, 
    ENROLMENTCHECK,
    HCHTIER,
    HCHSTARTED,
    HCHCURRENT,
    PENDINGMOBILECHANGE,
    GenderCode,
    PronounCode,
    DifferentIdentity, 
    ExtractionOptOut,
    eScriptDefault, 
    eScriptToken, 
    AtRiskOfCOVID, 
    VPE, 
    IHIValidation,
    MCOLverifydate,
    UseMBAddress, 
    PublicFunding,
    FinDependant,
    CSCHolder,
    HUCHolder, 
    CSCNumber, 
    IncSuppNumber, 
    HUCNumber, 
    CSCValid, 
    CSCExpiry, 
    HUCValid, 
    HUCExpiry, 
    IWI, 
    OVERALL_PATIENTVERSION, 
    CORE_VERSION, 
    MOH_CHECKED,
    COUNTRYOFBIRTH, 
    COUNTRYOFBIRTH_SOURCE,
    PLACEOFBIRTH, 
    CITIZEN,
    CITIZEN_SOURCE,
    DATEOFDEATHSOURCE,
    NAME_SOURCE,
    NAME_SETID, 
    NAME_VERSION,
    NAME_TYPE, 
    ADDRESS_GEOTAG, 
    ADDRESS_SETID, 
    ADDRESS_VERSION,
    ADDRESS_DOMICILE, 
    ADDRESS_NOTVALID_REASON,
    ESAM_CHECKED, 
    POSTAL_SUBURB, 
    POSTAL_ADDRESS_GEOTAG, 
    POSTAL_ADDRESS_DOMICILE,
    POSTAL_ADDRESS_NOTVALID_REASON,
    POSTAL_ESAM_CHECKED, 
    DOB_SOURCE, 
    ETHNIC1CODE, 
    ETHNIC2CODE
) VALUES (
    1, 
    'Active', 
    1001, 
    'IHI123456789', 
    'Valid', 
    'Active', 
    'Hospital', 
    'Web', 
    'Current', 
     NULL, 
     'Mr', 
     'John', 
     'Michael', 
     'Doe', 
    'Johnny', 
    '123 Main St', 
    'Apt 4B', 
    'Metropolis', 
    '12345', 
    '456 Secondary St', 
    'Uptown', 
    '67890', 
    '1980-01-01', 
     'M', 
     'ETH001', 
    '555-1234', 
    '555-5678', 
    '555-8765', 
    '1234567890', 
     '1', 
    '2025-01-01',
     'P001', 
     'PN12345', 
     '2020-01-01', 
     '2025-01-01',
      'D001', 
    'DVA12345', 
    'SN12345', 
    'RN12345', 
    'Christianity', 
    'HF12345', 
    'Health Fund Name', 
    'HFID12345', 
    '2025-01-01', 
    'AC12345', 
     101, 
    TRUE, 
    TRUE, 
    'Email', 
    201, 
    301, 
    401, 
    'Dr. Smith', 
    '2024-01-01', 
    'REF12345', 
     TRUE, 
     TRUE, 
     TRUE, 
     1, 
     TRUE, 
    'No additional notes.', 
    TRUE, 
    '2023-01-01 10:00:00', 
    'Admin', 
    '2024-01-01 12:00:00', 
    'Admin', 
    'CountryName', 
    'CountryName', 
     TRUE, 
    'Default', 
     102, 
     103, 
    104, 
     TRUE, 
     TRUE, 
     TRUE, 
    'HCH001', 
    '2024-01-01', 
    '2024-01-01', 
    '555-9999', 
    'G001', 
    'P001', 
     TRUE, 
     TRUE, 
     TRUE, 
    'eScriptToken', 
    TRUE, 
    'VPE12345', 
    TRUE, 
   '2024-01-01', 
    TRUE, 
    TRUE, 
    'Financial Dependent Name', 
     TRUE, 
     TRUE, 
    'CSC12345', 
    'INC12345', 
    'HUC12345', 
    TRUE, 
    '2025-01-01', 
     TRUE, 
    '2025-01-01', 
    'IWI12345', 
      1, 
      1, 
     TRUE, 
     'CountryOfBirth', 
     'Source',
     'PlaceOfBirth', 
      TRUE, 
     'Source', 
     'Source', 
     'Source', 
      1, 
      1, 
     'Legal', 
     'GeoTag', 
      1, 
      1, 
     'Domicile', 
     'Reason', 
      TRUE, 
     'Suburb', 
     'PostalGeoTag', 
     'PostalDomicile', 
     'PostalReason', 
      TRUE, 
     'DOBSource', 
      'ETH002', 
      'ETH003'
);



CREATE TABLE PRODUCTS (
    PRODUCTID INT NOT NULL,
    RECORDSTATUS INT NULL,
    PRODUCTNAMEID INT NOT NULL,
    STRENGTH CHAR(250) NULL,
    LISTORDER INT NULL,
    FORMCODE INT NOT NULL,
    PRODUCTDESCRIPTION CHAR(250) NULL,
    COMPANYFORM CHAR(150) NULL,
    DOSAGE VARCHAR(500) NULL,
    GLUTENCODE INT NOT NULL,
    BREASTCODE INT NOT NULL,
    SPORTCODE INT NOT NULL,
    PREGNANCYCODE INT NOT NULL,
    INTCHECK INT NOT NULL,
    DISEASECHECK INT NOT NULL,
    NOTEID INT NULL,
    PICODE INT NULL,
    CMICODE INT NULL,
    COMPANYID INT NULL,
    ROUTEID INT NULL,
    EAN INT NULL,
    GENERICNAME VARCHAR(2000) NULL,
    USESTRENGTH INT NOT NULL,
    MIMSBMCODE INT NULL,
    MIMSFORMCODE INT NULL,
    MIMSPACKCODE INT NULL,
    UPDATED DATETIME NULL,
    IsGeneric INT NOT NULL,
    IncludeBrand INT NOT NULL,
    UseBrandName INT NOT NULL,
    TGACategory INT NOT NULL,
    AU INT NOT NULL,
    NZ INT NOT NULL,
    PRIMARY KEY (PRODUCTID)
);


INSERT INTO PRODUCTS (
     PRODUCTID,
     RECORDSTATUS,
     PRODUCTNAMEID,
     STRENGTH,
     LISTORDER,
     FORMCODE,
     PRODUCTDESCRIPTION,
     COMPANYFORM,
     DOSAGE,
     GLUTENCODE,
     BREASTCODE,
     SPORTCODE,
     PREGNANCYCODE,
     INTCHECK,
     DISEASECHECK,
     NOTEID,
     PICODE,
     CMICODE,
     COMPANYID,
     ROUTEID,
     EAN,
     GENERICNAME,
     USESTRENGTH,
     MIMSBMCODE,
     MIMSFORMCODE,
     MIMSPACKCODE,
     UPDATED,
     IsGeneric,
     IncludeBrand,
     UseBrandName,
     TGACategory,
     AU,
     NZ
 ) VALUES (
     1,
     1,
     1001,
     '50mg',
     1,
     200,
     'Sample product description',
     'Sample Company Form',
     'Twice daily',
     1,
     0,
     1,
     1,
     1,
     1,
     NULL,
     500,
     600,
     700,
     800,
     12345,
     'Sample Generic Name',
     1,
     900,
     901,
     902,
     '2023-01-20T10:30:00',
     1,
     1,
     1,
     100,
     1,
     1
 );


CREATE TABLE APPOINTMENTS (
    RECORDID INT NOT NULL,
    INTERNALID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    USERID INT NOT NULL,
    LOCATIONID INT NOT NULL,
    VISITID INT NOT NULL,
    APPOINTMENTDATE DATETIME NOT NULL,
    APPOINTMENTTIME INT NOT NULL,
    APPOINTMENTLENGTH INT NOT NULL,
    APPOINTMENTCODE INT NOT NULL,
    APPOINTMENTTYPE INT NOT NULL,
    URGENT INT NOT NULL,
    REASON VARCHAR(500) NULL,
    ARRIVALTIME INT NOT NULL,
    CONSULTATIONTIME INT NOT NULL,
    VISITLENGTH INT NOT NULL,
    ROOMID INT NOT NULL,
    OPERATIONID INT NOT NULL,
    BOOKEDBY INT NOT NULL,
    ACCOUNTTYPE INT NOT NULL,
    NNAC INT NOT NULL,
    PATIENTS INT NOT NULL,
    ITEMLIST VARCHAR(2000) NULL,
    COMMENT VARCHAR(500) NULL,
    REMINDERSENT INT NULL,
    REMINDERSENTDATE DATETIME NULL,
    REMINDERSENTUSERID INT NULL,
    ATTENDANCECONFIRMED INT NULL,
    ATTENDANCEUPDATED DATETIME NULL,
    ATTENDANCEUPDATEDBY INT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    FOLLOWUP INT NOT NULL,
    VIDEOURL VARCHAR(2000) NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO APPOINTMENTS (
     RECORDID,
     INTERNALID,
     RECORDSTATUS,
     USERID,
     LOCATIONID,
     VISITID,
     APPOINTMENTDATE,
     APPOINTMENTTIME,
     APPOINTMENTLENGTH,
     APPOINTMENTCODE,
     APPOINTMENTTYPE,
     URGENT,
     REASON,
     ARRIVALTIME,
     CONSULTATIONTIME,
     VISITLENGTH,
     ROOMID,
     OPERATIONID,
     BOOKEDBY,
     ACCOUNTTYPE,
     NNAC,
     PATIENTS,
     ITEMLIST,
     COMMENT,
     REMINDERSENT,
     REMINDERSENTDATE,
     REMINDERSENTUSERID,
     ATTENDANCECONFIRMED,
     ATTENDANCEUPDATED,
     ATTENDANCEUPDATEDBY,
     CREATED,
     CREATEDBY,
     UPDATED,
     UPDATEDBY,
     FOLLOWUP,
     VIDEOURL
 ) VALUES (
     1,
     1001,
     1,
     200,
     300,
     400,
     '2023-01-20',
     1430,
     30,
     500,
     1,
     0,
     'Routine check-up',
     1415,
     15,
     20,
     600,
     700,
     800,
     900,
     1,
     100,
     'Medication, X-ray',
     'Additional comments here',
     0,
     NULL,
     NULL,
     0,
     NULL,
     NULL,
     '2023-4-5',
     2,
     '2023-04-05',
     NULL,
     2,
     'https://example.com/video'
 );


CREATE TABLE PRODUCTNAMES (
    PRODUCTNAMEID INT NOT NULL,
    PRODUCTNAME CHAR(100) NOT NULL,
    SEARCHNAME CHAR(100) NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME,
    AU INT NOT NULL,
    NZ INT NOT NULL,
    PRIMARY KEY (PRODUCTNAMEID)
);


INSERT INTO PRODUCTNAMES (
    PRODUCTNAMEID,
    PRODUCTNAME,
    SEARCHNAME,
    RECORDSTATUS,
    UPDATED,
    AU,
    NZ
) VALUES (
    1,
    'Sample Product',
    'Sample Product Search',
    1,
    '2023-01-20',
    1,
    1
);



CREATE TABLE PRODUCTINTERACTIONS (
    PRODUCTID INT NOT NULL,
    TERMID INT NOT NULL,
    INTERACTIONID INT NOT NULL,
    SEVERITY INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME,
    PRIMARY KEY (PRODUCTID, TERMID, INTERACTIONID)
);


INSERT INTO PRODUCTINTERACTIONS (
    PRODUCTID,
    TERMID,
    INTERACTIONID,
    SEVERITY,
    RECORDSTATUS,
    UPDATED
) VALUES (
    1,
    1001,
    2001,
    3,
    1,
    '2023-01-20T12:15:00'
);


CREATE TABLE PRODUCT_INGREDIENT (
    PRODUCTID INT NOT NULL,
    INGREDIENTID INT NOT NULL,
    STRENGTH CHAR(20),
    STRENGTHUNIT CHAR(30),
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME,
    PRINTORDER INT NOT NULL,
    PRIMARY KEY (PRODUCTID, INGREDIENTID)
);


INSERT INTO PRODUCT_INGREDIENT (
    PRODUCTID,
    INGREDIENTID,
    STRENGTH,
    STRENGTHUNIT,
    RECORDSTATUS,
    UPDATED,
    PRINTORDER
) VALUES (
    1,
    1001,
    '10',
    'mg',
    1,
    '2023-01-20T09:30:00',
    1
);



CREATE TABLE TERMCODES (
    TERMID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    TERMCODE CHAR(20),
    DOCLE CHAR(50),
    ICPC CHAR(10),
    ICD10 CHAR(10),
    SIDE INT,
    CHRONICITY INT,
    SEVERITY INT,
    STABILITY INT,
    FRACTURE INT,
    UPDATED DATETIME,
    PRIMARY KEY (TERMID)
);


INSERT INTO TERMCODES (
    TERMID,
    RECORDSTATUS,
    TERMCODE,
    DOCLE,
    ICPC,
    ICD10,
    SIDE,
    CHRONICITY,
    SEVERITY,
    STABILITY,
    FRACTURE,
    UPDATED
) VALUES (
    1,
    1,
    'TERM001',
    'Sample Docle',
    'A00',
    'J01.0',
    1,
    2,
    3,
    4,
    0,
    '2023-01-20T11:45:00'
);


CREATE TABLE INTERACTIONS (
    INTERACTIONID INT NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    UPDATED DATETIME,
    PRIMARY KEY (INTERACTIONID)
);

INSERT INTO INTERACTIONS (
    INTERACTIONID,
    DESCRIPTION,
    UPDATED
) VALUES (
    1,
    'Sample interaction description.',
    '2023-01-20T14:20:00'
);


CREATE TABLE DISEASEINTERACTIONS (
    RecordID INT NOT NULL,
    DRUGID INT NOT NULL,
    TERMID INT NOT NULL,
    INTERACTIONID INT NOT NULL,
    SEVERITY INT NOT NULL,
    UPDATED DATETIME,
    PRIMARY KEY (RecordID)
);


INSERT INTO DISEASEINTERACTIONS (
    RecordID,
    DRUGID,
    TERMID,
    INTERACTIONID,
    SEVERITY,
    UPDATED
) VALUES (
    1,
    1001,
    2001,
    3001,
    2,
    '2023-01-20T16:45:00'
);


CREATE TABLE DRUGINTERACTIONS (
    RECORDID INT NOT NULL, 			 
    DRUGID INT NOT NULL,
    INTERACTSWITH INT NOT NULL,
    INTERACTIONTYPE INT NOT NULL,
    INTERACTIONID INT NOT NULL,
    SEVERITY INT NOT NULL,
    UPDATED DATETIME,
    PRIMARY KEY (RECORDID)
);


INSERT INTO DRUGINTERACTIONS (
    RECORDID,
    DRUGID,
    INTERACTSWITH,
    INTERACTIONTYPE,
    INTERACTIONID,
    SEVERITY,
    UPDATED
) VALUES (
    1,
    1001,
    2001,
    1,
    3001,
    3,
    '2023-01-20T18:30:00'
);


CREATE TABLE BhcAppointment (
    BhcAppointmentId INT AUTO_INCREMENT PRIMARY KEY,
    AppointmentId INT NOT NULL,
    RecordStatus INT NOT NULL,
    UserMeetingCode VARCHAR(38) NULL,
    PatientMeetingUrl VARCHAR(1000) NULL,
    Status INT NOT NULL,
    Created DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    Updated DATETIME NULL,
    UpdatedBy INT NULL,
    Token VARCHAR(20) NULL
);


INSERT INTO BhcAppointment (
    AppointmentId, 
    RecordStatus, 
    UserMeetingCode, 
    PatientMeetingUrl, 
    Status, 
    Created, 
    CreatedBy, 
    Updated, 
    UpdatedBy, 
    Token

) VALUES (
    1234, 
    1, 
   'ABCDE1234567890', 
   'https://example.com/meeting_url', 
    1, 
   '2024-05-30 12:00:00', 
    5678, 
    NULL, 
    NULL, 
   'TOKEN123'
);


CREATE TABLE USERS (
    USERID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    USERSTATUS INT NOT NULL,
    LOCATIONID INT NOT NULL,
    HPII CHAR(16) NULL,
    GROUPCODE INT NOT NULL,
    TITLECODE INT NOT NULL,
    SURNAME CHAR(100) NOT NULL,
    FIRSTNAME CHAR(30) NOT NULL,
    PASSWORD VARCHAR(64) NULL,
    REGISTRATIONNO CHAR(20) NULL,
    CPDNO CHAR(10) NULL,
    PRESCRIBERNO CHAR(7) NULL,
    PROVIDERNO CHAR(8) NULL,
    PHONE CHAR(14) NULL,
    FAX CHAR(14) NULL,
    HOMEPHONE CHAR(14) NULL,
    MOBILEPHONE CHAR(14) NULL,
    PAGER CHAR(14) NULL,
    EMAIL VARCHAR(250) NULL,
    ABN CHAR(14) NULL,
    PKIKEY CHAR(12) NULL,
    TOPPOCKET INT NOT NULL,
    INACTIVEDATE DATETIME NULL,
    APPOINTMENTS INT NOT NULL,
    ACCOUNTS INT NOT NULL,
    DEFAULTACCOUNT INT NOT NULL,
    DEFAULTITEM CHAR(20) NULL,
    VR INT NOT NULL,
    LMO INT NOT NULL,
    REI INT NOT NULL,
    SENDHEL INT NOT NULL,
    TEDDSS INT NOT NULL,
    NEEDSREFERRAL INT NOT NULL,
    CONFIDENTIALNOTES INT NOT NULL,
    ERXID CHAR(10) NULL,
    THUMBPRINT CHAR(40) NULL,
    COMPANYNAME VARCHAR(150) NULL,
    OPERATIONS INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    HPIIVALIDATED DATETIME NULL,
    MEDREFERTOKEN VARCHAR(64) NULL,
    SendApp BIT NOT NULL,
    SRAStatus INT NOT NULL,
    SRALastSynchronised DATETIME NULL,
    SRAID VARCHAR(32) NULL,
    BUSINESSNAME VARCHAR(100) NULL,
    PasswordSalt VARCHAR(32) NULL,
    NZMCNUMBER CHAR(10) NULL,
    ACCPAYEENUMBER CHAR(10) NULL,
    GMSPAYEENUMBER CHAR(10) NULL,
    PRIMARY KEY (USERID)
);

INSERT INTO USERS (
    RECORDSTATUS,
    USERSTATUS,
    LOCATIONID,
    HPII,
    GROUPCODE,
    TITLECODE,
    SURNAME,
    FIRSTNAME,
    PASSWORD,
    REGISTRATIONNO,
    CPDNO,
    PRESCRIBERNO,
    PROVIDERNO,
    PHONE,
    FAX,
    HOMEPHONE,
    MOBILEPHONE,
    PAGER,
    EMAIL,
    ABN,
    PKIKEY,
    TOPPOCKET,
    INACTIVEDATE,
    APPOINTMENTS,
    ACCOUNTS,
    DEFAULTACCOUNT,
    DEFAULTITEM,
    VR,
    LMO,
    REI,
    SENDHEL,
    TEDDSS,
    NEEDSREFERRAL,
    CONFIDENTIALNOTES,
    ERXID,
    THUMBPRINT,
    COMPANYNAME,
    OPERATIONS,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    HPIIVALIDATED,
    MEDREFERTOKEN,
    SendApp,
    SRAStatus,
    SRALastSynchronised,
    SRAID,
    BUSINESSNAME,
    PasswordSalt,
    NZMCNUMBER,
    ACCPAYEENUMBER,
    GMSPAYEENUMBER
) VALUES (
    1,
    1,
    1001,
    '0123',
    2001,
    3001,
    'Doe',
    'John',
    'hashed_password',
    'REG123',
    'CPD456',
    'PRE123',
    'PROV456',
    '123-456-7890',
    '987-654-3210',
    '555-123-4567',
    '555-987-6543',
    '789-123-4567',
    'john.doe@example.com',
    'ABN12',
    'PKI6',
    23,
    NULL,
    2,
    3,
    4,
    'ITEM123',
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    'ERXID123',
    'THUMBPRINT123',
    'Sample Company',
    5,
    '2023-01-20T22:00:00',
    400,
    NULL,
    '2',
    '2023-01-21',
    0,
    1,
    2,
    '2023-01-21',
    'SRAID123',
    'Sample Business',
    'Salt123',
    'NZMC456',
    'ACC89',
    'GMSP2'
);



CREATE TABLE CONTACTDETAILS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    CONTACTID INT NOT NULL,
    ADDRESSCODE INT NOT NULL,
    ADDRESS1 CHAR(60) NULL,
    ADDRESS2 CHAR(60) NULL,
    CITY CHAR(40) NULL,
    POSTCODE CHAR(4) NULL,
    EMAIL VARCHAR(250) NULL,
    PHONE CHAR(14) NULL,
    FAX CHAR(14) NULL,
    HPIO CHAR(16) NULL,
    HSDKEY CHAR(36) NULL,
    HSDUPDATE DATETIME NULL,
    CAPABILITIES VARCHAR(1000) NULL,
    COMMENT VARCHAR(1000) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    HPIOVALIDATED DATETIME NULL,
    HL7_24 BIT NOT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO CONTACTDETAILS (
    RECORDSTATUS,
    CONTACTID,
    ADDRESSCODE,
    ADDRESS1,
    ADDRESS2,
    CITY,
    POSTCODE,
    EMAIL,
    PHONE,
    FAX,
    HPIO,
    HSDKEY,
    HSDUPDATE,
    CAPABILITIES,
    COMMENT,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    HPIOVALIDATED,
    HL7_24
) VALUES (
    1,
    1001,
    2001,
    '123 Main Street',
    'Apt 456',
    'Cityville',
    '1234',
    'contact@example.com',
    '555-123-4567',
    '555-789-0123',
    'HPI',
    'HSDK',
    '2023-01-20',
    'Sample capabilities',
    'Additional comment',
    '2023-01-20',
    300,
    NULL,
    NULL,
    '2023-01-20',
    1
);


CREATE TABLE EREFERRALS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    RECIPIENTID INT NOT NULL,
    DOCUMENTID INT NOT NULL,
    STATUSCODE INT NOT NULL,
    MESSAGEID CHAR(60) NULL,
    STOREDDATE DATETIME NULL,
    TRANSMITDATE DATETIME NULL,
    ACKCODE INT NOT NULL,
    ACKDATE DATETIME NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    MESSAGINGPROVIDERID INT NULL,
    DETAILS VARCHAR(99) NULL,
    NOTIFIED BIT NOT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO EREFERRALS (
    RECORDSTATUS,
    INTERNALID,
    USERID,
    RECIPIENTID,
    DOCUMENTID,
    STATUSCODE,
    MESSAGEID,
    STOREDDATE,
    TRANSMITDATE,
    ACKCODE,
    ACKDATE,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    MESSAGINGPROVIDERID,
    DETAILS,
    NOTIFIED
) VALUES (
    1,
    1001,
    2001,
    3001,
    4001,
    1,
    'MSG123456789',
    '2023-01-20T12:30:00',
    '2023-01-21T08:45:00',
    2,
    '2023-01-21T09:15:00',
    '2023-01-20T09:00:00',
    500,
    NULL,
    NULL,
    600,
    'Sample referral details',
    1
);



CREATE TABLE BIRTHS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    PREGNANCYID INT NOT NULL,
    INTERNALID INT NOT NULL,
    FIRSTNAME CHAR(30) NULL,
    SEX INT NOT NULL,
    WEIGHT CHAR(4) NULL,
    LIVE INT NOT NULL,
    APGAR1 INT NOT NULL,
    APGAR5 INT NOT NULL,
    BIRTHORDER INT NOT NULL,
    CHILD_ID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO BIRTHS (
    RECORDSTATUS, 
    PREGNANCYID, 
    INTERNALID, 
    FIRSTNAME, 
    SEX, 
    WEIGHT,  
    LIVE, 
    APGAR1, 
    APGAR5, 
    BIRTHORDER, 
    CHILD_ID, 
    CREATED, 
    CREATEDBY
) VALUES (
    1,
    1234, 
    5678,
    'Emily',
    1, 
   '3.2',
    1, 
    8, 
    10, 
    1, 
    1, 
   '2024-05-30 12:00:00',
    789
);



CREATE TABLE PREGNANCIES (
    PREGNANCYID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    PREGNANCYNUMBER INT NOT NULL,
    EDCBYDATE DATETIME NULL,
    EDCBYSCAN DATETIME NULL,
    USESCAN INT NOT NULL,
    SCANDAYS INT NOT NULL,
    SCANWEEKS INT NOT NULL,
    CERTAINTY INT NOT NULL,
    SCANDATE DATETIME NULL,
    ACTUALLMP DATETIME NULL,
    NOMINALLMP DATETIME NULL,
    ENDDATE DATETIME NULL,
    GESTATIONLENGTH INT NOT NULL,
    IVF INT NOT NULL,
    GDM INT NOT NULL,
    HYPERTENSION INT NOT NULL,
    ECLAMPSIA INT NOT NULL,
    RENALDISEASE INT NOT NULL,
    OUTCOMECODE INT NOT NULL,
    STAGE1LABOUR CHAR(5) NULL,
    STAGE2LABOUR CHAR(5) NULL,
    STAGE3LABOUR CHAR(5) NULL,
    ONSETCODE INT NOT NULL,
    DELIVERYCODE INT NOT NULL,
    AUGMENTATIONCODE INT NOT NULL,
    ANALGESIACODE INT NOT NULL,
    PERINEUMCODE INT NOT NULL,
    PLACENTACODE INT NOT NULL,
    BLOODLOSSCODE INT NOT NULL,
    ANTI_D INT NOT NULL,
    FEEDINGCODE INT NOT NULL,
    PNBLEEDING INT NOT NULL,
    PNAMENORRHOEA INT NOT NULL,
    PNCSWOUND INT NOT NULL,
    PNPERINEUM INT NOT NULL,
    PNUTERUS INT NOT NULL,
    PNCONTRACEPTION INT NOT NULL,
    PNDEPRESSION INT NOT NULL,
    DELIVERYNOTES VARCHAR(2000) NULL,
    PNVISITNOTES VARCHAR(2000) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (PREGNANCYID)
);

INSERT INTO PREGNANCIES (
    RECORDSTATUS, 
    INTERNALID, 
    USERID, 
    PREGNANCYNUMBER, 
    EDCBYDATE, 
    EDCBYSCAN, 
    USESCAN, 
    SCANDAYS, 
    SCANWEEKS,
    CERTAINTY, 
    SCANDATE, 
    ACTUALLMP, 
    NOMINALLMP, 
    ENDDATE, 
    GESTATIONLENGTH, 
    IVF, 
    GDM, 
    HYPERTENSION, 
    ECLAMPSIA, 
    RENALDISEASE, 
    OUTCOMECODE, 
    STAGE1LABOUR, 
    STAGE2LABOUR, 
    STAGE3LABOUR,
    ONSETCODE, 
    DELIVERYCODE, 
    AUGMENTATIONCODE,  
    ANALGESIACODE, 
    PERINEUMCODE, 
    PLACENTACODE, 
    BLOODLOSSCODE, 
    ANTI_D, 
    FEEDINGCODE, 
    PNBLEEDING, 
    PNAMENORRHOEA, 
    PNCSWOUND, 
    PNPERINEUM, 
    PNUTERUS, 
    PNCONTRACEPTION, 
    PNDEPRESSION,
    DELIVERYNOTES, 
    PNVISITNOTES, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    1001, 
    5678,
    1, 
    NULL, 
   '2024-05-30 12:00:00', 
    1, 
    7,
    10, 
    1, 
   '2024-05-30 12:00:00', 
   '2024-01-01',
   '2024-01-01', 
   '2024-09-30', 
    40,
    0, 
    1, 
    0, 
    0, 
    0, 
    1, 
   'Yes', 
   'Yes', 
   'Yes',
    1,
    1, 
    1, 
    1, 
    1, 
    1, 
    1, 
    1, 
    1, 
    1, 
    0, 
    0, 
    1, 
    0, 
    1, 
    1,
    'SHE IS', 
    'during her first visit she is doing fine', 
    '2024-05-30 12:00:00', 789,
     null, 
     null
);



CREATE TABLE TOBACCO (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    SMOKINGCODE INT NOT NULL,
    SMOKINGTYPE INT NOT NULL,
    SMOKESPERDAY INT NOT NULL,
    YEARSTARTED INT NOT NULL,
    PASTSMOKINGCODE INT NOT NULL,
    PASTSMOKESPERDAY INT NOT NULL,
    PASTSTARTED INT NOT NULL,
    PASTSTOPPED INT NOT NULL,
    COMMENT VARCHAR(1000) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    CESSATION INT NOT NULL,
    ADVICE INT NOT NULL,
    MEDICATION INT NOT NULL,
    SUPPORT INT NOT NULL,
    REFERRAL INT NOT NULL,
    PRIMARY KEY (RECORDID)
);


INSERT INTO TOBACCO (
    RECORDSTATUS,
    INTERNALID,
    SMOKINGCODE,
    SMOKINGTYPE,
    SMOKESPERDAY,
    YEARSTARTED,
    PASTSMOKINGCODE,
    PASTSMOKESPERDAY,
    PASTSTARTED,
    PASTSTOPPED,
    COMMENT,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    CESSATION,
    ADVICE,
    MEDICATION,
    SUPPORT,
    REFERRAL
) VALUES (
    1,
    1001,
    2001,
    1,
    10,
    2010,
    2,
    5,
    2005,
    2015,
    'Patient quit smoking for health reasons.',
    '2023-01-20T14:30:00',
    300,
    NULL,
    NULL,
    1,
    1,
    0,
    1,
    1
);


CREATE TABLE CLINICAL (
    INTERNALID INT NOT NULL,
    KNOWNALLERGIES INT NOT NULL,
    PASTHISTORY INT NOT NULL,
    FAMILYHISTORY INT NOT NULL,
    SMOKINGSTATUS INT NOT NULL,
    ALCOHOLSTATUS INT NOT NULL,
    BLOODGROUP CHAR(2) NULL,
    RH INT NOT NULL,
    RETIRED INT NOT NULL,
    MARITALSTATUS INT NOT NULL,
    SEXUALITY INT NOT NULL,
    ELITESPORTS INT NOT NULL,
    PACEMAKER INT NOT NULL,
    SOCIALHX VARCHAR(1000) NULL,
    RECREATION VARCHAR(1000) NULL,
    ACCOMODATION INT NULL,
    LIVESWITH INT NULL,
    HASCARER INT NULL,
    ISCARER INT NULL,
    WEBSTER INT NOT NULL,
    CAUSEOFDEATH CHAR(60) NULL,
    CAUSEOFDEATHCODE INT NOT NULL,
    OTHERCOMMENT VARCHAR(1000) NULL,
    DRNOTE LONGBLOB NULL,
    HIDEDRNOTE INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PCEHR INT NOT NULL,
    SHS DATETIME NULL,
    SAFEINHOME INT NOT NULL,
    ACD INT NULL,
    POWEROFATTORNEY INT NULL,
    NIR INT NOT NULL,
    DRNOTECOMPLETEDUSERID INT NOT NULL,
    PRIMARY KEY (INTERNALID)
);


INSERT INTO CLINICAL (
    INTERNALID,
    KNOWNALLERGIES,
    PASTHISTORY,
    FAMILYHISTORY,
    SMOKINGSTATUS,
    ALCOHOLSTATUS,
    BLOODGROUP,
    RH,
    RETIRED,
    MARITALSTATUS,
    SEXUALITY,
    ELITESPORTS,
    PACEMAKER,
    SOCIALHX,
    RECREATION,
    ACCOMODATION,
    LIVESWITH,
    HASCARER,
    ISCARER,
    WEBSTER,
    CAUSEOFDEATH,
    CAUSEOFDEATHCODE,
    OTHERCOMMENT,
    DRNOTE,
    HIDEDRNOTE,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    PCEHR,
    SHS,
    SAFEINHOME,
    ACD,
    POWEROFATTORNEY,
    NIR,
    DRNOTECOMPLETEDUSERID
) VALUES (
    1001,
    1,
    1,
    1,
    2,
    3,
    'AB',
    1,
    0,
    2,
    1,
    0,
    1,
    'Patient has no significant social history.',
    'Enjoys hiking and gardening.',
    3,
    4,
    0,
    1,
    1,
    'Natural causes',
    1001,
    'Additional comments about the patient.',
    NULL,
    0,
    '2023-01-20T16:15:00',
    200,
    NULL,
    NULL,
    1,
    '2023-01-21T09:45:00',
    1,
    0,
    1,
    0,
    1
);


CREATE TABLE MESSAGINGPROVIDERS (
    MESSAGINGPROVIDERID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    PROVIDERNAME CHAR(100) NULL,
    ACCOUNTID CHAR(20) NULL,
    PATHIN VARCHAR(1000) NULL,
    PATHOUT VARCHAR(1000) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    USECDA INT NOT NULL,
    INCLUDEOBXTEXT BIT NOT NULL,
    ALLOWSACK INT NOT NULL,
    NamespaceID VARCHAR(200) NULL,
    UniversalID VARCHAR(200) NULL,
    UniversalIDType VARCHAR(200) NULL,
    PRIMARY KEY (MESSAGINGPROVIDERID)
);


INSERT INTO MESSAGINGPROVIDERS (
    RECORDSTATUS,
    PROVIDERNAME,
    ACCOUNTID,
    PATHIN,
    PATHOUT,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    USECDA,
    INCLUDEOBXTEXT,
    ALLOWSACK,
    NamespaceID,
    UniversalID,
    UniversalIDType
) VALUES (
    1,
    'Sample Provider',
    'ACC123',
    '/inbox',
    '/outbox',
    '2023-01-20T18:45:00',
    100,
    NULL,
    NULL,
    1,
    1,
    1,
    'http://www.example.com/namespace',
    '12345',
    'ISO'
);



CREATE TABLE PREGNANCYIMAGING (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    INTERNALID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    PREGNANCYID INT NOT NULL,
    TESTNAME CHAR(80) NULL,
    SEQUENCE INT NOT NULL,
    RESULTID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);


INSERT INTO PREGNANCYIMAGING (
    INTERNALID,
    RECORDSTATUS,
    PREGNANCYID,
    TESTNAME,
    SEQUENCE,
    RESULTID,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY
) VALUES (
    1001,
    1,
    2001,
    'Ultrasound',
    1,
    3001,
    '2023-01-20T20:30:00',
    400,
    NULL,
    NULL
);

-- /Table 21  *********************************/

CREATE TABLE ALCOHOL (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    DAYSPERWEEK INT NOT NULL,
    DRINKSPERDAY INT NOT NULL,
    ALCOHOLCODE INT NOT NULL,
    ALCOHOLTEXT VARCHAR(100) NULL,
    PASTDAYSPERWEEK INT NOT NULL,
    PASTDRINKSPERDAY INT NOT NULL,
    PASTALCOHOLLEVEL INT NOT NULL,
    YEARSTARTED INT NOT NULL,
    YEARSTOPPED INT NOT NULL,
    COMMENT VARCHAR(500) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO ALCOHOL (
    RECORDSTATUS, 
    INTERNALID, 
    DAYSPERWEEK,
    DRINKSPERDAY, 
    ALCOHOLCODE, 
    ALCOHOLTEXT,
    PASTDAYSPERWEEK,
    PASTDRINKSPERDAY, 
    PASTALCOHOLLEVEL,
    YEARSTARTED, 
    YEARSTOPPED, 
    COMMENT, 
    CREATED, 
    CREATEDBY, 
    UPDATEDBY
) VALUES (
    1, 
    1234, 
    7, 
    2, 
    1, 
   'Beer', 
    5,
    1, 
    3, 
    2010,
    2020, 
   'No comment', 
    NOW(),
    999, 
    NULL
);


-- /Table 22  *********************************/

CREATE TABLE ADRAC (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    RECDATE DATETIME NULL,
    WEIGHT CHAR(5) NULL,
    DRUGNAME VARCHAR(100) NULL,
    PRODUCTID INT NOT NULL,
    FORM CHAR(3) NULL,
    FREQUENCY CHAR(2) NULL,
    ROUTE CHAR(6) NULL,
    BATCH CHAR(15) NULL,
    DOSE CHAR(50) NULL,
    STARTDATE DATETIME NULL,
    STOPDATE DATETIME NULL,
    INDICATION VARCHAR(100) NULL,
    ONSETDATE DATETIME NULL,
    REACTION VARCHAR(100) NULL,
    REACFREQ CHAR(1) NULL,
    DESCRIPTION TEXT NULL,
    SEVERITY CHAR(1) NULL,
    TREATEDAT CHAR(1) NULL,
    TREATMENT TEXT NULL,
    OUTCOME CHAR(1) NULL,
    OUTDATE DATETIME NULL,
    COMMENTS TEXT NULL,
    SEQUELAE TEXT NULL,
    INCLUDERX CHAR(1) NULL,
    INCLUDEPMH CHAR(1) NULL,
    MESSAGEID CHAR(8) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO ADRAC (
    INTERNALID, 
    USERID, 
    RECORDSTATUS, 
    RECDATE,  
    WEIGHT, 
    DRUGNAME, 
    PRODUCTID, 
    FORM, 
    FREQUENCY, 
    ROUTE, 
    BATCH, 
    DOSE, 
    STARTDATE, 
    STOPDATE, 
    INDICATION, 
    ONSETDATE, 
    REACTION, 
    REACFREQ, 
    DESCRIPTION, 
    SEVERITY, 
    TREATEDAT, 
    TREATMENT, 
    OUTCOME, 
    OUTDATE, 
    COMMENTS, 
    SEQUELAE, 
    INCLUDERX, 
    INCLUDEPMH, 
    MESSAGEID, 
    CREATED, 
    CREATEDBY, 
    UPDATEDBY
) VALUES (
    1234, 
    5678,
    1, 
   '2024-05-30 12:00:00', 
   '70kg', 
   'Paracetamol',
    123, 
    'Tab', 
     2, 
    'Oral', 
    '123456789', 
    '500mg',
    '2024-05-30 12:00:00', 
    '2024-05-31 12:00:00', 
    'Headache',
    '2024-05-30 12:00:00', 
    'Nausea', 
    'A',
    'No Description', 
    'M', 
    'A', 
    'Rest',
    'C', 
    '2024-05-31 12:00:00', 
    'No comments',
    'No sequelae', 
    'Y', 
    'Y', 
    'ABC12345',
    '2024-05-30 12:00:00',
     999, 
     NULL
);


-- /Table 23  *********************************/

CREATE TABLE SMSSCHEDULES (
    SCHEDULEID INT AUTO_INCREMENT NOT NULL,
    SCHEDULENAME VARCHAR(50) NOT NULL,
    DATESPAN CHAR(20) NOT NULL,
    DAYSAHEAD INT NULL,
    SEARCHBYTIME INT NOT NULL,
    SEARCHTIMESTART INT NULL,
    SEARCHTIMEEND INT NULL,
    EXCLUDEALREADYSENT INT NOT NULL,
    EXCLUDERECENT INT NOT NULL,
    EXCLUDERECENTDAYS INT NULL,
    SCHEDULE CHAR(20) NOT NULL,
    SCHEDULEDAY CHAR(20) NULL,
    SCHEDULEMONTH CHAR(20) NULL,
    SENDTIME INT NOT NULL,
    TEMPLATEID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    SENDSMS INT NOT NULL,
    SENDAPP INT NOT NULL,
    TIMEPRIOR INT NOT NULL,
    PRIMARY KEY (SCHEDULEID)
);
INSERT INTO SMSSCHEDULES (
    SCHEDULENAME, 
    DATESPAN, 
    DAYSAHEAD, 
    SEARCHBYTIME, 
    SEARCHTIMESTART, 
    SEARCHTIMEEND, 
    EXCLUDEALREADYSENT, 
    EXCLUDERECENT, 
    EXCLUDERECENTDAYS, 
    SCHEDULE, 
    SCHEDULEDAY, 
    SCHEDULEMONTH, 
    SENDTIME, 
    TEMPLATEID, 
    CREATED, 
    CREATEDBY, 
    SENDSMS, 
    SENDAPP, 
    TIMEPRIOR
) VALUES (
    'Morning Reminder', 
    'Daily',
     1,
     1, 
     800, 
     1000, 
     1, 
     1, 
     2, 
    'Daily', 
     NULL,
     NULL, 
     730, 
     123, 
     NOW(), 
     999, 
     1, 
     0, 
     30
);


-- /Table 24  *********************************/

CREATE TABLE SMSSCHEDULE_USER (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    SCHEDULEID INT NOT NULL,
    USERID INT NOT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO SMSSCHEDULE_USER (
    SCHEDULEID, 
    USERID
)VALUES (
    123, 
    456
);



-- /Table 25  *********************************/

CREATE TABLE SMSSCHEDULE_LOCATION (
    RecordID INT AUTO_INCREMENT NOT NULL,
    ScheduleID INT NOT NULL,
    LocationID INT NOT NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO SMSSCHEDULE_LOCATION (
    ScheduleID, 
    LocationID
)VALUES (
    123, 
    789
);


-- /Table 26  *********************************/

CREATE TABLE SMSSCHEDULE_APPTTYPE (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    APPOINTMENTCODE INT NOT NULL,
    SCHEDULEID INT NOT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO SMSSCHEDULE_APPTTYPE (
    APPOINTMENTCODE, 
    SCHEDULEID
)
VALUES (
    123, 
    456
);


-- /Table 27  *********************************/

CREATE TABLE TESTITEMS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    REQUESTID INT NOT NULL,
    TESTCODE CHAR(100) NULL,
    TESTNAME VARCHAR(100) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO TESTITEMS (
    RECORDSTATUS, 
    REQUESTID, 
    TESTCODE, 
    TESTNAME, 
    CREATED, 
    CREATEDBY, 
    UPDATEDBY
)
VALUES (
     1, 
     789, 
    'ABC123', 
    'Test Item',
     NOW(), 
     999, 
     NULL
);




 -- REQUESTEDTESTS Table
CREATE TABLE REQUESTEDTESTS (
    REQUESTID INT AUTO_INCREMENT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    LOCATIONID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    REQUESTTYPE INT NOT NULL,
    REQUESTDATE DATETIME NOT NULL,
    REQUESTSTATUS INT NOT NULL,
    PROVIDERID INT NOT NULL,
    PROVIDERNAME VARCHAR(100) NULL,
    FREETEXTITEM VARCHAR(1000) NULL,
    FASTING INT NOT NULL,
    PREGNANT INT NOT NULL,
    LMP DATETIME NULL,
    EDC DATETIME NULL,
    URGENT INT NOT NULL,
    URGENTBY CHAR(7) NULL,
    URGENTPHONE CHAR(14) NULL,
    URGENTFAX CHAR(14) NULL,
    CLINICALDETAILS VARCHAR(1000) NULL,
    SMEARSITE INT NOT NULL,
    CERVIX INT NOT NULL,
    EROSION INT NOT NULL,
    ECTROPION INT NOT NULL,
    POSTNATAL INT NOT NULL,
    POSTMENOPAUSAL INT NOT NULL,
    OCP INT NOT NULL,
    HRT INT NOT NULL,
    HYSTERECTOMY INT NOT NULL,
    RADIORX INT NOT NULL,
    IUD INT NOT NULL,
    BLEEDING INT NOT NULL,
    COPIES VARCHAR(1500) NULL,
    BILLING INT NOT NULL,
    PAPREGISTER INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    VisitId INT NULL,
    VisitUpdated INT NOT NULL,
    LABREQUESTID VARCHAR(50) NULL,
    MODALITY INT NOT NULL,
    CONSENT INT NOT NULL,
    PMBleeding INT NOT NULL,
    IMBleeding INT NOT NULL,
    PCBleeding INT NOT NULL,
    PVDischarge INT NOT NULL,
    Dyspareunia INT NOT NULL,
    PreviousAIS INT NOT NULL,
    TestOfCure INT NOT NULL,
    Immunodeficient INT NOT NULL,
    DESExposure INT NOT NULL,
    PreviousUnsatisfactory INT NOT NULL,
    PreviousAbnormal INT NOT NULL,
    SelfCollected INT NOT NULL,
    EarlyDebut INT NOT NULL,
    SUBTOTAL INT NOT NULL,
    BARCODE VARCHAR(50) NULL,
    PRIMARY KEY (REQUESTID)
);

-- Insert one sample row
INSERT INTO REQUESTEDTESTS (
    INTERNALID, 
    USERID, 
    LOCATIONID, 
    RECORDSTATUS, 
    REQUESTTYPE, 
    REQUESTDATE, 
    REQUESTSTATUS, 
    PROVIDERID, 
    PROVIDERNAME, 
    FREETEXTITEM,
    FASTING, 
    PREGNANT, 
    LMP, 
    EDC, 
    URGENT, 
    URGENTBY, 
    URGENTPHONE, 
    URGENTFAX, 
    CLINICALDETAILS, 
    SMEARSITE, 
    CERVIX, 
    EROSION, 
    ECTROPION,
    POSTNATAL, 
    POSTMENOPAUSAL, 
    OCP, 
    HRT, 
    HYSTERECTOMY, 
    RADIORX, 
    IUD, 
    BLEEDING, 
    COPIES, 
    BILLING, 
    PAPREGISTER, 
    CREATED, 
    CREATEDBY,
    UPDATED, 
    UPDATEDBY, 
    VisitId, 
    VisitUpdated, 
    LABREQUESTID, 
    MODALITY, 
    CONSENT, 
    PMBleeding, 
    IMBleeding, 
    PCBleeding, 
    PVDischarge,
    Dyspareunia, 
    PreviousAIS, 
    TestOfCure, 
    Immunodeficient, 
    DESExposure, 
    PreviousUnsatisfactory, 
    PreviousAbnormal, 
    SelfCollected,
    EarlyDebut, 
    SUBTOTAL, 
    BARCODE
) VALUES (
    1001, 
    2001, 
    3001, 
    1, 
    2, 
   '2024-02-08 10:30:00',
    3, 
    4001, 
    'Dr. Smith', 
   'Additional tests needed',
    0, 
    1, 
   '2024-01-15', 
   '2024-09-01', 
    1, 
   'Dr.Doe', 
   '1234567', 
   '5678901234', 
   'Patient has symptoms of XYZ',
    1, 
    1, 
    1, 
    1, 
    0, 
    1, 
    0, 
    0, 
    1, 
   1, 
    1, 
    1, 
   '2024-02-08 10:30:00',
    5001,
    1, 
    '2024-07-06', 
    6001, 
    '2023-06-07', 
    1, 
    0, 
    1, 
    1, 
    1, 
    1, 
    1, 
    1,
    0, 
    0, 
    1, 
    1, 
    0, 
    0, 
    0, 
    1, 
    0, 
    1, 
    1, 
    1,
   'ABC123'
);




-- /Table 29  *********************************/

CREATE TABLE PAYMENTS (
    PAYMENTID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    LOCATIONID INT NOT NULL,
    PAYMENTDATE DATETIME NULL,
    REFERENCE CHAR(30) NULL,
    PAYERCODE INT NOT NULL,
    PAYERID INT NOT NULL,
    DETAILID INT NOT NULL,
    AMOUNT INT NOT NULL,
    PREPAYMENT INT NOT NULL,
    PAYMENTRUNNUM INT NOT NULL,
    PAYMENTRUNDATE DATETIME NULL,
    BATCHNUMBER CHAR(10) NULL,
    PROVIDERNO CHAR(10) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PAYMENTCODE INT NOT NULL,
    PAYMENTLINKID INT NOT NULL,
    PRIMARY KEY (PAYMENTID)
);
INSERT INTO PAYMENTS (
    RECORDSTATUS, 
    LOCATIONID, 
    PAYMENTDATE, 
    REFERENCE, 
    PAYERCODE, 
    PAYERID, 
    DETAILID, 
    AMOUNT, 
    PREPAYMENT, 
    PAYMENTRUNNUM, 
    PAYMENTRUNDATE, 
    BATCHNUMBER, 
    PROVIDERNO, 
    CREATED, 
    CREATEDBY, 
    UPDATEDBY, 
    PAYMENTCODE, 
    PAYMENTLINKID
)
VALUES (
    1, 
    2345, 
   '2024-05-30 12:00:00', 
   'Payment123', 
    567,
    890, 
    1234, 
    100, 
    0, 
    1,
    NULL,
   'BATCH001',
   'PROV123',
    NOW(),
    999,
    NULL,
    123, 
    456
);


-- /Table 30  *********************************/

CREATE TABLE DRUGSHEETS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    SHEETNAME CHAR(50) NOT NULL,
    SHEETTITLE CHAR(150) NULL,
    PORTRAIT INT NOT NULL,
    HASLINES INT NOT NULL,
    DRUGSPERPAGE INT NOT NULL,
    DAYSPERPAGE INT NOT NULL,
    TIMESPERDAY INT NOT NULL,
    TOPMARGIN INT NOT NULL,
    LEFTMARGIN INT NOT NULL,
    BOTTOMMARGIN INT NOT NULL,
    RIGHTMARGIN INT NOT NULL,
    TITLETOP INT NOT NULL,
    TITLELEFT INT NOT NULL,
    NAMETOP INT NOT NULL,
    NAMELEFT INT NOT NULL,
    ADDRESSTOP INT NOT NULL,
    ADDRESSLEFT INT NOT NULL,
    DOCTORTOP INT NOT NULL,
    DOCTORLEFT INT NOT NULL,
    DOBTOP INT NOT NULL,
    DOBLEFT INT NOT NULL,
    MEDICARETOP INT NOT NULL,
    MEDICARELEFT INT NOT NULL,
    ALLERGIESTOP INT NOT NULL,
    ALLERGIESLEFT INT NOT NULL,
    DATETOP INT NOT NULL,
    DATELEFT INT NOT NULL,
    RECORDTOP INT NOT NULL,
    RECORDLEFT INT NOT NULL,
    DRUGSTOP INT NOT NULL,
    DRUGSLEFT INT NOT NULL,
    PRNSEPARATE INT NOT NULL,
    GENERIC INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO DRUGSHEETS (
    RECORDSTATUS,  
    SHEETNAME, 
    SHEETTITLE, 
    PORTRAIT, 
    HASLINES, 
    DRUGSPERPAGE,
    DAYSPERPAGE,
    TIMESPERDAY, 
    TOPMARGIN, 
    LEFTMARGIN,
    BOTTOMMARGIN, 
    RIGHTMARGIN,
    TITLETOP,
    TITLELEFT, 
    NAMETOP,
    NAMELEFT,
    ADDRESSTOP,
    ADDRESSLEFT, 
    DOCTORTOP,
    DOCTORLEFT,
    DOBTOP, 
    DOBLEFT, 
    MEDICARETOP,
    MEDICARELEFT, 
    ALLERGIESTOP, 
    ALLERGIESLEFT,
    DATETOP,
    DATELEFT,
    RECORDTOP, 
    RECORDLEFT,  
    DRUGSTOP,
    DRUGSLEFT, 
    PRNSEPARATE, 
    GENERIC,
    CREATED, 
    CREATEDBY, 
    UPDATEDBY
 )
VALUES (
    1,
   'Sheet1',
   'Drug Sheet', 
    1, 
    1,
    10, 
    7,
    4,
    10, 
    20,
    10,
    20, 
    30, 
    40, 
    50,
    60, 
    70, 
    80, 
    90, 
    100,
    120,
    130,
    140, 
    150,
    160,
    170, 
    180,
    190,
    200, 
    210, 
    220, 
    230, 
    240,
    250,
    NOW(), 
    999,
    NULL
);



-- /Table 31 *********************************/

-- DRUGCOMBINATIONS Table
CREATE TABLE DRUGCOMBINATIONS (
    COMBINATIONID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    USERID INT NOT NULL,
    COMBINATIONNAME CHAR(40) NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (COMBINATIONID)
);

INSERT INTO DRUGCOMBINATIONS (
    RECORDSTATUS, 
    USERID,
    COMBINATIONNAME,
    CREATED, 
    CREATEDBY,
    UPDATED,
    UPDATEDBY
) VALUES (
    1, 
    101,
   'Pain Relief Combo', 
   '2024-05-30 12:00:00',
    1001,
   '2024-05-30 12:30:00',
    1002
);


-- /Table 32 *********************************/

-- DISPENSEDITEMS Table
CREATE TABLE DISPENSEDITEMS (
    ITEMID INT AUTO_INCREMENT NOT NULL,
    INTERNALID INT NOT NULL,
    SCID CHAR(20) NULL,
    SEQUENCE INT NOT NULL,
    TRADENAME CHAR(50) NULL,
    PRODUCTID INT NOT NULL,
    PACKID INT NOT NULL,
    PHARMACYID INT NOT NULL,
    DISPENSEDATE DATETIME NULL,
    SUPPLYNUMBER INT NULL,
    DISPENSEDQUANTITY INT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PATIENTCONSENT TINYINT NULL,
    MEDICATIONMODIFIED TINYINT NULL,
    INSTRUCTIONSMODIFIED TINYINT NULL,
    FORCENOTIFICATION TINYINT NULL,
    PHARMACYNOTES TEXT NULL,
    CONFIDENTIALITYFLAG VARCHAR(2) NULL,
    PRIMARY KEY (ITEMID)
);

INSERT INTO DISPENSEDITEMS (
    INTERNALID, 
    SCID,
    SEQUENCE,
    TRADENAME, 
    PRODUCTID, 
    PACKID,
    PHARMACYID,
    DISPENSEDATE,
    SUPPLYNUMBER, 
    DISPENSEDQUANTITY, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY, 
    PATIENTCONSENT, 
    MEDICATIONMODIFIED, 
    INSTRUCTIONSMODIFIED, 
    FORCENOTIFICATION, 
    PHARMACYNOTES, 
    CONFIDENTIALITYFLAG
) VALUES
    (12345,
    'SCID001',
     1,
    'Drug A', 
     1001,
     2001, 
     3001, 
    '2024-05-29 09:00:00', 
     1, 
     30,
    '2024-05-30 12:00:00',
     101, 
    '2024-05-30 12:30:00', 
     102,
      1,
      0,
      0,
       1,
     'Take with water',
      'N'
);

-- /Table 33 *********************************/

-- APPOINTMENTTYPES Table
CREATE TABLE APPOINTMENTTYPES (
    APPOINTMENTCODE INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    LISTORDER INT NOT NULL,
    ICONINDEX INT NOT NULL,
    APPOINTMENTLENGTH INT NOT NULL,
    DESCRIPTION CHAR(250) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    AU INT NOT NULL,
    NZ INT NOT NULL,
    PRIMARY KEY (APPOINTMENTCODE)
);

INSERT INTO APPOINTMENTTYPES (
    RECORDSTATUS, 
    LISTORDER,
    ICONINDEX,
    APPOINTMENTLENGTH,
    DESCRIPTION,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY,
    AU,
    NZ
) VALUES (
    1,
    1,
    1,
    30,
   'General Check-up',
   '2024-05-30 12:00:00',
    101, 
   '2024-05-30 12:30:00',
    102,
    1,
    1
);

-- /Table 34 *********************************/

-- OPERATIONS Table
CREATE TABLE OPERATIONS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    OPERATIONSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    APPOINTMENTID INT NOT NULL,
    OPERATIONDATE DATETIME NOT NULL,
    OPERATIONTIME INT NOT NULL,
    OPERATIONCATEGORY INT NOT NULL,
    OPERATIONNAME VARCHAR(1000) NULL,
    OPERATIONDETAIL VARCHAR(1000) NULL,
    OPERATIONCODE INT NULL,
    MBSITEM CHAR(20) NULL,
    OPERATIONSIDE INT NOT NULL,
    ANAESTHETICCODE INT NOT NULL,
    OPERATIONLENGTH VARCHAR(75) NULL,
    ANAESTHETISTID INT NOT NULL,
    ASSISTANTID INT NOT NULL,
    FACILITYID INT NOT NULL,
    STAY INT NOT NULL,
    PREOPID INT NOT NULL,
    INDICATION VARCHAR(300) NULL,
    DESCRIPTION TEXT NULL,
    FINDINGS TEXT NULL,
    OUTCOME VARCHAR(1000) NULL,
    OUTCOMECODE INT NOT NULL,
    COMMENT VARCHAR(1000) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO OPERATIONS (
    RECORDSTATUS,
    OPERATIONSTATUS,
    INTERNALID,
    USERID,
    APPOINTMENTID,
    OPERATIONDATE,
    OPERATIONTIME,
    OPERATIONCATEGORY, 
    OPERATIONNAME, 
    OPERATIONDETAIL,
    OPERATIONCODE, 
    MBSITEM, 
    OPERATIONSIDE, 
    ANAESTHETICCODE, 
    OPERATIONLENGTH, 
    ANAESTHETISTID, 
    ASSISTANTID,
    FACILITYID,
    STAY, 
    PREOPID, 
    INDICATION,
    DESCRIPTION,
    FINDINGS,
    OUTCOME,
    OUTCOMECODE,
    COMMENT, 
    CREATED,
    CREATEDBY,  
    UPDATED,
    UPDATEDBY
) VALUES (
    1, 
    1, 
    12345,
    101,
    1001,
   '2024-05-28',
    930,
    1,
   'Appendectomy',
   'Removal of appendix',
    123, 
   'MBS001', 
    1, 
    101, 
   '1 hour', 
    201, 
    301, 
    401, 
    1,
    501, 
   'Acute appendicitis', 
   'Operation successful', 
   'Appendix removed', 
   'No complications', 
    1, 
   'Patient recovering well', 
   '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:30:00', 
    102
);

-- /Table 35 *********************************/

-- PAIN Table
CREATE TABLE PAIN (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    RECDATE DATETIME NULL,
    BODYSIDE INT NOT NULL,
    LOCATION INT NOT NULL,
    SEVERITY INT NOT NULL,
    COMMENT TEXT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO PAIN (
    RECORDSTATUS, 
    INTERNALID,
    USERID,
    RECDATE, 
    BODYSIDE,
    LOCATION, 
    SEVERITY, 
    COMMENT,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY
) VALUES
    (1,
     12345,
     101,
    '2024-05-28',
     1,
      3,
     5,
    'Moderate pain in left arm',
    '2024-05-30 12:00:00',
     101, 
    '2024-05-30 12:30:00',
     102
);

-- /Table 36 *********************************/

-- PAPSMEARS Table
CREATE TABLE PAPSMEARS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    PAPDATE DATETIME NOT NULL,
    PAPCODE INT NOT NULL,
    COMMENT VARCHAR(500) NULL,
    HPV INT NOT NULL,
    ENDOCERVICALCELLS INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    CST INT NOT NULL,
    HPV16 INT NOT NULL,
    HPV18 INT NOT NULL,
    HPVOTHER INT NOT NULL,
    RISKCODE INT NOT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO PAPSMEARS (
    RECORDSTATUS, 
    INTERNALID,
     USERID,
     PAPDATE,
    PAPCODE,
    COMMENT,
    HPV,
    ENDOCERVICALCELLS,
     CREATED,
    CREATEDBY, 
    UPDATED,
    UPDATEDBY,
    CST,
    HPV16, 
    HPV18,
    HPVOTHER,
    RISKCODE
) VALUES
    (1,
     12345,
     101,
    '2024-05-27', 
     202, 
    'Normal smear',
     0,
      1, 
   '2024-05-30 12:00:00',
     101,
    '2024-05-30 12:30:00',
     102,
     1,
     0,
     0,
     0,
     1
);

-- /Table 37 *********************************/

-- PARAMETERS Table
CREATE TABLE PARAMETERS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    DATADATE DATETIME NOT NULL,
    DATATIME INT NOT NULL,
    DATANAME CHAR(12) NOT NULL,
    DATAVALUE CHAR(12) NOT NULL,
    DATACODE INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO PARAMETERS (
    RECORDSTATUS, 
    INTERNALID,
    USERID,
    DATADATE, 
    DATATIME,
    DATANAME, 
    DATAVALUE, 
    DATACODE,
    CREATED, 
    CREATEDBY,
    UPDATED, 
    UPDATEDBY
) VALUES
    (1,
     12345,
     101,
    '2024-05-30', 
     1000, 
    'Blood',
    '120/80', 
     301,
    '2024-05-30 12:00:00',
     101, 
    '2024-05-30 12:30:00',
     102
);

#/Table 38 *********************************/

-- PASTHISTORY Table
CREATE TABLE PASTHISTORY (
    RECORDID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    YEAR INT NOT NULL,
    MONTH INT NOT NULL,
    DAY INT NOT NULL,
    ITEMTEXT VARCHAR(250),
    ITEMCODE INT NOT NULL,
    STATUSCODE INT NOT NULL,
    LOCATIONCODE INT NOT NULL,
    POSITIONCODE INT NOT NULL,
    DESCRIPTIONCODE INT NOT NULL,
    SEVERITYCODE INT NOT NULL,
    ACUTECODE INT NOT NULL,
    PRIVACYCODE INT NOT NULL,
    SUMMARYCODE INT NOT NULL,
    FRACTURE INT NOT NULL,
    DISPLACED INT NOT NULL,
    COMPOUND INT NOT NULL,
    COMMINUTED INT NOT NULL,
    SPIRAL INT NOT NULL,
    GREENSTICK INT NOT NULL,
    MOM CHAR(36),
    MOMPATH VARCHAR(500),
    DETAILS TEXT,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME,
    UPDATEDBY INT,
    PCEHR INT NOT NULL,
    PROVISIONAL INT NOT NULL,
    VisitId INT,
    VisitUpdated INT NOT NULL
);

INSERT INTO PASTHISTORY (
    RECORDSTATUS,
    INTERNALID,
     USERID,
     YEAR,
    MONTH,
    DAY,
    ITEMCODE,
    STATUSCODE,
    LOCATIONCODE, 
    POSITIONCODE,
    DESCRIPTIONCODE,
    SEVERITYCODE, 
    ACUTECODE,
    PRIVACYCODE,
    SUMMARYCODE,
    FRACTURE,
    DISPLACED,
    COMPOUND,
    COMMINUTED,
    SPIRAL,
    GREENSTICK,
    CREATED,
    CREATEDBY,
    UPDATEDBY,
    PCEHR,
    PROVISIONAL,
    VisitUpdated
) 
VALUES (1,
     1234, 
     5678,
     2024,
     5,
     30, 
     123,
      456,
     789, 
     987,
     654, 
     321,
     999, 
     888,
     777,
      0,
      1,
      1,
      1,
      0,
      0, 
     NOW(),
      999,
     NULL,
      1,
      1,
      1
);

#/Table 39 *********************************/
-- PATIENT_ENROLMENTS Table
CREATE TABLE PATIENT_ENROLMENTS (
    RECORDID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDTYPE INT,
    ENROLMENTID INT,
    INTERNALID INT NOT NULL,
    MODE VARCHAR(20) NOT NULL,
    HEALTH_SERVICE_CODE VARCHAR(20),
    STATUS INT,
    APPLICATION_DATE DATE,
    STARTDATE DATE,
    ENDDATE DATE,
    EXPIRYDATE DATE,
    TERMINATION_REASON_CODE VARCHAR(50),
    REENROLMENT_DATE DATE,
    LAST_ENCOUNTER_DATE DATE,
    ENROLLING_ORGANISATION_ID VARCHAR(255),
    ENROLLING_ORGANISATION_NAME VARCHAR(255),
    SERVICE_ORGANISATION_ID VARCHAR(255),
    SERVICE_PRACTITIONER_CPN VARCHAR(255),
    SERVICE_PRACTIIONER_NAME VARCHAR(255),
    SERVICE_FACILITY_ID VARCHAR(255),
    AUTHENTICATED_ORGID VARCHAR(255),
    LOCALPROCESSINGDATE DATE,
    CREATED DATETIME,
    CREATEDBY INT,
    UPDATED DATETIME,
    UPDATEDBY INT
);

INSERT INTO PATIENT_ENROLMENTS (
    RECORDTYPE, 
    ENROLMENTID, 
    INTERNALID, 
    MODE, 
    HEALTH_SERVICE_CODE, 
    STATUS,
    APPLICATION_DATE, 
    STARTDATE, 
    ENDDATE, 
    EXPIRYDATE, 
    TERMINATION_REASON_CODE,
    REENROLMENT_DATE, 
    LAST_ENCOUNTER_DATE,
    ENROLLING_ORGANISATION_ID, 
    ENROLLING_ORGANISATION_NAME, 
    SERVICE_ORGANISATION_ID, 
    SERVICE_PRACTITIONER_CPN,
    SERVICE_PRACTIIONER_NAME, 
    SERVICE_FACILITY_ID, 
    AUTHENTICATED_ORGID,
    LOCALPROCESSINGDATE, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    1001, 
    2001, 
    'ONLINE', 
    'HSC123', 
     1,
    '2024-05-01',
    '2024-05-10',
    '2024-11-10', 
    '2024-12-31', 
    'NONE',
    NULL, 
   '2024-05-15', 
   'ORG001', 
    'Health Org One', 
    'SVC001', 
    'CPN123',
    'Dr. John Doe', 
    'FAC001', 
    'AUTH001',
    '2024-05-02', 
    '2024-05-01 10:00:00',
     101, 
    '2024-05-05 14:30:00', 
     102
);

#/Table 40 *********************************/


-- PatientAppEnrolment Table
CREATE TABLE PatientAppEnrolment (
    RecordID INT AUTO_INCREMENT PRIMARY KEY,
    InternalID INT NOT NULL,
    RecordStatus INT NOT NULL,
    LocationID INT NOT NULL,
    EnrolmentStatus INT NOT NULL,
    PatientPublicKey VARCHAR(4000) NOT NULL,
    MobileNumber VARCHAR(30) NOT NULL,
    PatientAppUsername VARCHAR(255) NOT NULL,
    Created DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    Updated DATETIME,
    UpdatedBy INT,
    AppVersion VARCHAR(10)
);

INSERT INTO PatientAppEnrolment (
    InternalID, 
    RecordStatus, 
    LocationID, 
    EnrolmentStatus, 
    PatientPublicKey, 
    MobileNumber, 
    PatientAppUsername, 
    Created, 
    CreatedBy,
    Updated, 
    UpdatedBy, 
    AppVersion) 
VALUES (
    1234, 
    1, 
    5678, 
    1, 
   'PublicKey123', 
   '1234567890', 
   'Username123', 
    NOW(), 
    999,
    '2024-09-04',
    2, 
   '1.0'
);





#/Table 41 *********************************/

-- PATIENTBANKACCOUNTS Table
CREATE TABLE PATIENTBANKACCOUNTS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    BANKID INT NOT NULL,
    ACCOUNTNAME VARCHAR(250) NULL,
    ACCOUNTNUMBER CHAR(20) NULL,
    BSBNUMBER CHAR(20) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (RECORDID)
);
INSERT INTO PATIENTBANKACCOUNTS (
    RECORDSTATUS, 
    INTERNALID, 
    BANKID, 
    ACCOUNTNAME, 
    ACCOUNTNUMBER, 
    BSBNUMBER, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    12345, 
    1, 
   'John Doe', 
   '1234567890', 
   '0987654321', 
   '2024-05-30 12:34:56', 
    101, 
   '2024-05-30 12:45:00', 
    102
);


#/Table 42 *********************************/

-- PATIENTCLAIMS Table
CREATE TABLE PATIENTCLAIMS (
    RECORDID INT AUTO_INCREMENT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    USERID INT NOT NULL,
    INVOICEID INT NOT NULL,
    PAYMENTID INT NOT NULL,
    CLAIMDATE DATETIME NULL,
    CLAIMTIME CHAR(6) NULL,
    CLAIMSTATUS INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PMSClaimNo VARCHAR(30) NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO PATIENTCLAIMS (
    RECORDSTATUS, 
    INTERNALID, 
    USERID, 
    INVOICEID, 
    PAYMENTID, 
    CLAIMDATE, 
    CLAIMTIME, 
    CLAIMSTATUS, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY, 
    PMSClaimNo
) VALUES (
    1,
    12345, 
    201, 
    301, 
    401, 
   '2024-05-29', 
   '123456',
    1, 
   '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:30:00', 
    102, 
   'CLAIM123'
);


#/Table 43 *********************************/

-- PATIENTCONSENT Table
CREATE TABLE PATIENTCONSENT (
    INTERNALID INT NOT NULL,
    ENROLLEDSMS INT NOT NULL,
    CONSENTEMAIL INT NOT NULL,
    APPOINTMENTREMINDERS INT NOT NULL,
    CLINICALREMINDERS INT NOT NULL,
    CLINICALAWARENESS INT NOT NULL,
    HEALTHAWARENESS INT NOT NULL,
    SIGNEDCONSENT INT NULL,
    OPTOUT INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL,
    PRIMARY KEY (INTERNALID)
);
INSERT INTO PATIENTCONSENT (
    INTERNALID, 
    ENROLLEDSMS, 
    CONSENTEMAIL, 
    APPOINTMENTREMINDERS,
    CLINICALREMINDERS, 
    CLINICALAWARENESS, 
    HEALTHAWARENESS, 
    SIGNEDCONSENT, 
    OPTOUT, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    12345, 
    1, 
    1, 
    1, 
    0, 
    1, 
    0, 
    1, 
    0, 
   '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:20:00', 
    102
);



#/Table 44 *********************************/

-- PATIENTETHNICITY Table
CREATE TABLE PATIENTETHNICITY (
    RECORDID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    ETHNICCODE INT NOT NULL,
    PRIORITY INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL
);
INSERT INTO PATIENTETHNICITY (
    RECORDSTATUS, 
    INTERNALID, 
    ETHNICCODE, 
    PRIORITY, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    12345,
    5, 
    1, 
    '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:30:00', 
    102
);




#/Table 45 *********************************/

-- PATIENTPHOTO Table
CREATE TABLE PATIENTPHOTO (
    PHOTOID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    INTERNALID INT NOT NULL,
    STOREID INT NOT NULL,
    CURRENT INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL
);
INSERT INTO PATIENTPHOTO (
    RECORDSTATUS, 
    INTERNALID, 
    STOREID, 
    CURRENT, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    12345, 
    1, 
    1,
    '2024-05-30 12:00:00',
    101,
   '2024-05-30 12:30:00',
    102
);





#/Table 46 *********************************/

-- PatientPresence Table
CREATE TABLE PatientPresence (
    RecordID INT AUTO_INCREMENT PRIMARY KEY,
    RecordStatus INT NOT NULL,
    Presence INT NOT NULL,
    AppointmentID INT NOT NULL,
    Created DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    Updated DATETIME NULL,
    UpdatedBy INT NULL
);
INSERT INTO PatientPresence (
    RecordStatus, 
    Presence, 
    AppointmentID, 
    Created, 
    CreatedBy, 
    Updated, 
    UpdatedBy
) VALUES (
    1, 
    1, 
    501, 
   '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:20:00', 
    102
);



#/Table 47 *********************************/

-- PAYER Table
CREATE TABLE PAYER (
    PAYERID INT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    TITLECODE INT NOT NULL,
    SURNAME CHAR(100) NULL,
    FIRSTNAME CHAR(30) NULL,
    ADDRESS1 CHAR(60) NULL,
    ADDRESS2 CHAR(60) NULL,
    CITY CHAR(40) NULL,
    POSTCODE CHAR(4) NULL,
    PHONE CHAR(14) NULL,
    FAX CHAR(14) NULL,
    EMAIL VARCHAR(250) NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL
);
INSERT INTO PAYER (
    PAYERID, 
    RECORDSTATUS, 
    TITLECODE, 
    SURNAME, 
    FIRSTNAME, 
    ADDRESS1, 
    ADDRESS2, 
    CITY, 
    POSTCODE, 
    PHONE, 
    FAX, 
    EMAIL, 
    CREATED, 
    CREATEDBY, 
    UPDATED, 
    UPDATEDBY
) VALUES (
    1, 
    1, 
    1, 
   'Doe', 
   'John', 
   '123 Main St', 
   'Apt 4B', 
   'Springfield', 
   '1234', 
   '1234567890', 
   '0987654321', 
   'john.doe@example.com', 
   '2024-05-30 12:00:00', 
    101, 
   '2024-05-30 12:30:00', 
    102
);



#/Table 48 *********************************/

-- PAYMENT_SERVICE Table
CREATE TABLE PAYMENT_SERVICE (
    RECORDID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    PAYMENTID INT NOT NULL,
    SERVICEID INT NOT NULL,
    AMOUNT INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL
);
INSERT INTO PAYMENT_SERVICE (
    RECORDSTATUS,
    PAYMENTID,
    SERVICEID,
    AMOUNT,
    CREATED,
    CREATEDBY,
    UPDATED,
    UPDATEDBY
) VALUES
    (1,
     601,
     701,
     100,
    '2024-05-30 12:00:00', 
     101,
    '2024-05-30 12:30:00', 
     102
);




#/Table 49 *********************************/

-- PaymentClaims Table
CREATE TABLE PaymentClaims (
    RECORDID INT AUTO_INCREMENT PRIMARY KEY,
    RECORDSTATUS INT NOT NULL,
    PAYMENTRUNID INT NULL,
    PAYMENTRUNDATE DATETIME NULL,
    BATCHID INT NULL,
    CLAIMID CHAR(10) NULL,
    CLAIMDATE DATETIME NULL,
    AMOUNTCLAIMED INT NOT NULL,
    CLAIMBENEFITPAID INT NOT NULL,
    CREATED DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    UPDATED DATETIME NULL,
    UPDATEDBY INT NULL
);
INSERT INTO PaymentClaims (
    RECORDSTATUS, 
    PAYMENTRUNID,
    PAYMENTRUNDATE,
    BATCHID,
    CLAIMID,
    CLAIMDATE, 
    AMOUNTCLAIMED,
    CLAIMBENEFITPAID,
    CREATED,
    CREATEDBY,
    UPDATED, 
    UPDATEDBY
) VALUES
    (1,
     801, 
    '2024-05-29', 
     901,
     'CLAIM001',
     '2024-05-28',
      150,
      120,
     '2024-05-30 12:00:00',
       101,
     '2024-05-30 12:30:00',
      102
);

#/Table 50 *********************************/

-- UserNumbers Table
CREATE TABLE UserNumbers (
    RecordID INT AUTO_INCREMENT PRIMARY KEY,
    RecordStatus INT NOT NULL,
    UserID INT NULL,
    NumberType INT NOT NULL,
    NumberValue VARCHAR(20) NOT NULL,
    Created DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    Updated DATETIME NULL,
    UpdatedBy INT NULL
);

INSERT INTO UserNumbers (
    RecordStatus, 
    UserID,
    NumberType,
    NumberValue,
    Created,
    CreatedBy, 
    Updated, 
    UpdatedBy
) VALUES
    (1, 
     1001,
      1,
    '555-1234',
    '2024-05-30 12:00:00', 
     101,
    '2024-05-30 12:20:00',
     102
);



-- DietRecords Table
CREATE TABLE DietRecords (
    RecordID INT PRIMARY KEY AUTO_INCREMENT ,
    DietID INT,
    INTERNALID INT,
    MealType VARCHAR(50),
    FoodItem VARCHAR(255),
    Quantity NUMERIC,
    Calories NUMERIC,
    Date DATE,
    Time TIME,
    DietaryPreference VARCHAR(50),
    DietaryRestrictions VARCHAR(255),
    VegetarianType VARCHAR(50),
    Notes TEXT,
    FOREIGN KEY (INTERNALID) REFERENCES Patients(INTERNALID)
);

INSERT INTO DietRecords (
    DietID,
    INTERNALID,
    MealType,
    FoodItem,
    Quantity,
    Calories,
    Date, 
    Time, 
    DietaryPreference,
    DietaryRestrictions,
    VegetarianType,
    Notes
)
VALUES
    (1,
     1, 
    'Breakfast',
    'Oatmeal',
     200,
     150,
    '2024-02-08',
    '08:00:00',
    'Vegetarian',
    'Gluten-free',
    'Lacto-vegetarian',
    'High in fiber and protein.'
);




/* Table 52 *********************************/

-- ActivityRecords Table
CREATE TABLE ActivityRecords (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    ActivityID INT,
    INTERNALID INT,
    ActivityType VARCHAR(50),
    Duration NUMERIC,
    Intensity VARCHAR(50),
    Date DATE,
    Time TIME,
    Location VARCHAR(255),
    Mood VARCHAR(255),
    Notes TEXT,
    FOREIGN KEY (INTERNALID) REFERENCES Patients(INTERNALID)
);

INSERT INTO ActivityRecords (
    ActivityID,
    INTERNALID,
    ActivityType,
    Duration,
    Intensity, 
    Date,
    Time,
    Location,
    Mood,
    Notes
)
VALUES
    (1, 
     1, 
    'Running',
     30,
    'High', 
    '2024-02-08', 
    '09:30:00',
     'Park', 
    'Energized',
    'Morning jog for cardio health.'
);



/* Table 53 *********************************/

-- DoctorTypes Table
CREATE TABLE DoctorTypes (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    DoctorTypeID INT,
    DoctorTypeName VARCHAR(255),
    Description TEXT,
    PracticeType VARCHAR(50),
    CertificationRequired BOOLEAN,
    RegulatoryBody VARCHAR(255),
    Notes TEXT
);

INSERT INTO DoctorTypes (
    DoctorTypeID,
    DoctorTypeName,
    Description,
    PracticeType, 
    CertificationRequired, 
    RegulatoryBody,
    Notes
)
VALUES
    (1, 
     001,
    'General Practitioner', 
    'Provides primary and preventive care', 
    1,
      TRUE,
   'Medical Council of India (MCI)'
);


/* Table 54 *********************************/

-- PatientInformation Table
CREATE TABLE PatientInformation (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    INTERNALID INT,
    Name VARCHAR(255),
    Age INT,
    Gender VARCHAR(20),
    Location VARCHAR(255),
    Height NUMERIC,
    Weight NUMERIC,
    BMI NUMERIC,
    WaistCircumference NUMERIC,
    ArmCircumference NUMERIC,
    DailyCaloricIntake NUMERIC,
    ProteinIntake NUMERIC,
    Micronutrients TEXT,
    Edema BOOLEAN,
    HairChanges BOOLEAN,
    SkinChanges BOOLEAN,
    ExistingConditions TEXT,
    Medication TEXT,
    FoodSecurity VARCHAR(50),
    EconomicStatus VARCHAR(50)
);

INSERT INTO PatientInformation (
    INTERNALID,
    Name,
    Age,
    Gender, 
    Location,
    Height,
    Weight,
    BMI,
    WaistCircumference, 
    ArmCircumference,
    DailyCaloricIntake,
    ProteinIntake,
    Micronutrients,
    Edema,
    HairChanges, 
    SkinChanges,
    ExistingConditions,
    Medication,
    FoodSecurity,
    EconomicStatus
)
VALUES
    (1,
    'John Doe', 
     30,
    'Male',
    'Nairobi, Kenya',
    175,
    2,
    22,
     85,
    30,
    2000,
    80,
   'Vitamin C, Iron',
    FALSE,
    TRUE,
    FALSE,
    'None',
    'None',
    'Food Secure',
    'Middle Class'
);


/* Table 55 *********************************/

-- NutritionTools Table
CREATE TABLE NutritionTools (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    ToolID INT,
    ToolCategory VARCHAR(255),
    ToolName VARCHAR(255),
    Description TEXT,
    Application VARCHAR(255)
);

INSERT INTO NutritionTools (
    ToolID,
    ToolCategory,
    ToolName,
    Description,
    Application
)
VALUES
    (1, 
    'Dietary Assessment Tools',
    '24-Hour Dietary Recall',
    'Estimates daily food and nutrient intake',
    'Interview'
);


/* Table 56 ********************************/

-- FFQData Table
CREATE TABLE FFQData (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    FFQID INT,
    INTERNALID INT,
    DateCompleted DATE,
    FoodItemID INT,
    Frequency VARCHAR(50),
    PortionSize VARCHAR(50),
    TimeFrame VARCHAR(50),
    Notes TEXT,
    FOREIGN KEY (INTERNALID) REFERENCES Patients(INTERNALID)
);

INSERT INTO FFQData (
    FFQID, 
    INTERNALID,
    DateCompleted,
    FoodItemID,
    Frequency,
    PortionSize, 
    TimeFrame,
    Notes
)
VALUES
    (1,
     1,
    '2024-02-08',
     1,
    'Daily',
    '1 cup', 
    'Past Month',
    'Regular consumption of oatmeal for breakfast.'
);



/* Table 57 *********************************/

-- FoodItems Table
CREATE TABLE FoodItems (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    FoodItemID INT,
    FoodName VARCHAR(255),
    FoodGroup VARCHAR(50),
    ServingSize VARCHAR(50),
    Notes TEXT
);

INSERT INTO FoodItems (
    FoodItemID,
    FoodName,
    FoodGroup,
    ServingSize,
    Notes
)
VALUES
    (1,
    'Oatmeal',
    'Grains',
    '1 cup',
    'Rich in fiber and nutrients.'
);


/* Table 58 *********************************/

-- DemographicData Table
CREATE TABLE DemographicData (
    RecordID INT PRIMARY KEY AUTO_INCREMENT,
    PatientID INT,
    Name VARCHAR(255),
    Age INT,
    Gender VARCHAR(50),
    DateOfBirth DATE,
    Location VARCHAR(255),
    Ethnicity VARCHAR(255),
    PrimaryLanguage VARCHAR(50),
    EducationLevel VARCHAR(50),
    Occupation VARCHAR(50),
    SocioeconomicStatus VARCHAR(50),
    HouseholdComposition TEXT,
    AccessToHealthcare VARCHAR(50),
    HealthInsuranceStatus VARCHAR(50),
    NutritionSecurity VARCHAR(50),
    WaterSource VARCHAR(50),
    SanitationFacilities VARCHAR(50),
    ElectricityAccess BOOLEAN,
    MobileOrInternetAccess BOOLEAN,
    TransportationAccess VARCHAR(50)
);

INSERT INTO DemographicData (
     PatientID, 
     Name,
     Age,
     Gender,
     DateOfBirth,
     Location,
     Ethnicity,
     PrimaryLanguage, 
     EducationLevel,
     Occupation,
     SocioeconomicStatus,
     HouseholdComposition,
     AccessToHealthcare,
     HealthInsuranceStatus,
     NutritionSecurity,
     WaterSource, 
     SanitationFacilities,
     ElectricityAccess,
     MobileOrInternetAccess,
     TransportationAccess
)
VALUES
    (1,
    'John Doe',
     30,
    'Male',
   '1992-05-15',
   'Nairobi, Kenya',
   'Kikuyu',
    'Swahili',
    'Bachelor' 's Degree',
    'Software Engineer',
    'Middle Class',
    'Family of 4 (Parents, 2 Children)',
     'Yes',
     'Yes', 
    'Food Secure',
    'Tap Water',
    'Flush Toilet',
     1, 
     1,
    'Public Transportation'
);



/*********************************/



CREATE TABLE Post_Office (
    RecordId INT AUTO_INCREMENT PRIMARY KEY,
    officename VARCHAR(255),
    pincode INT,
    officeType VARCHAR(50),
    Deliverystatus VARCHAR(50),
    divisionname VARCHAR(255),
    regionname VARCHAR(255),
    circlename VARCHAR(255),
    Taluk VARCHAR(255),
    Districtname VARCHAR(255),
    statename VARCHAR(255),
    Telephone VARCHAR(50),
    Related_Suboffice VARCHAR(255),
    Related_Headoffice VARCHAR(255),
    longitude VARCHAR(50),
    latitude VARCHAR(50)
);


INSERT INTO Post_Office (
    officename,
    pincode, 
    officeType,
    Deliverystatus, 
    divisionname, 
    regionname,
    circlename,
    Taluk,
    Districtname, 
    statename, 
    Telephone,
    Related_Suboffice, 
    Related_Headoffice,
    longitude, 
    latitude
)
VALUES (
    'Main Post Office',
     123456, 
    'Head Office',
    'Delivery', 
    'Central Division', 
    'North Region', 
    'Zone 1',
    'Taluk A',  
    'District X', 
    'State Y',
    '123-456-7890',
    'Sub Office 1', 
    'Head Office 1',
    '75.123456',
    '15.123456'
);


CREATE TABLE AVAILABILITY (
    PACKID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRODUCTUNIT VARCHAR(50) NOT NULL,
    DOSEPERUNIT INT NOT NULL,
    MBMCODE INT NULL,
    FORMCODE INT NULL,
    PACKCODE INT NULL,
    PBSDRUGCODE CHAR(6) NULL,
    PBSCOMPANYCODE CHAR(2) NULL,
    REPEATS INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME NULL,
    AMTTPPCODE CHAR(18) NULL,
    AMTMPPCODE CHAR(18) NULL,
    NOBREAK INT NOT NULL,
    PRIMARY KEY (PACKID)
);

INSERT INTO AVAILABILITY (
    PACKID, 
    PRODUCTID,
    QUANTITY,
    PRODUCTUNIT,
    DOSEPERUNIT,
    MBMCODE,
    FORMCODE,
    PACKCODE, 
    PBSDRUGCODE,
    PBSCOMPANYCODE, 
    REPEATS,
    RECORDSTATUS,
    UPDATED,
    AMTTPPCODE,
    AMTMPPCODE,
    NOBREAK
) VALUES (
    1, 
    101, 
    20,
    'Tablet',
     500,
     123,
     10,
    2001,
   'AB1234',
   '01', 
    2,
    1,
   '2024-05-30 12:00:00',
   'TPPCODE1234567890',
   'MPPCODE1234567890',
    0
);




CREATE TABLE CAREPLANITEMS (
    RECORDID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    ITEMTYPE INT NOT NULL,
    ITEMTEXT VARCHAR(250) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO CAREPLANITEMS (
    RECORDID, 
    RECORDSTATUS,
    ITEMTYPE,
    ITEMTEXT,
    UPDATED
)
VALUES (
    1,
    1, 
    2, 
   'Initial assessment completed',
   '2024-05-30 14:25:00'
);



CREATE TABLE CATEGORIES (
    CATEGORYCODE INT NOT NULL,
    CATEGORYTYPE INT NOT NULL,
    CATEGORYNAME CHAR(40) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (CATEGORYCODE)
);

INSERT INTO CATEGORIES (
    CATEGORYCODE,
    CATEGORYTYPE,
    CATEGORYNAME,
    UPDATED
)
VALUES (
    101,
    1, 
   'General Medicine',
   '2024-05-30 14:00:00'
);




CREATE TABLE CEASEDREASONS (
    Reason VARCHAR(100) NULL,
    ReasonCode INT NULL,
    UPDATED DATETIME NULL
); 
INSERT INTO CEASEDREASONS (
    Reason,
    ReasonCode,
    UPDATED
)
VALUES (
   'Retired',
    1,
   '2024-05-30 14:00:00'
);
 



CREATE TABLE ClassRef (
    RecordID INT NOT NULL,
    RecordStatus INT NOT NULL,
    CLASSNAME CHAR(50) NOT NULL,
    BPSID INT NULL,
    UPDATED DATETIME NOT NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO ClassRef (
    RecordID,
    RecordStatus,
    CLASSNAME,
    BPSID,
    UPDATED
)
VALUES (
    1,
    1, 
    'Mathematics', 
    1001, 
   '2024-05-30 14:00:00'
);


CREATE TABLE CLINICALDETAILS (
    ITEMID INT NOT NULL,
    ITEMNAME CHAR(100) NOT NULL,
    ITEMTYPE INT NULL,
    LABCODE INT NOT NULL,
    UPDATED CHAR(10) NULL,
    PRIMARY KEY (ITEMID)
);

INSERT INTO CLINICALDETAILS (
    ITEMID,
    ITEMNAME,
    ITEMTYPE,
    LABCODE,
    UPDATED
)
VALUES (
    1,
   'Blood Test',
    2,
    3001, 
   '2024-05-30'
);



CREATE TABLE CLINICALTEXT (
    RECORDID INT NOT NULL,
    ITEMNAME CHAR(30) NULL,
    ITEMCODE INT NOT NULL,
    ITEMTYPE INT NOT NULL,
    OBJECTCODE INT NOT NULL,
    ITEM1 CHAR(50) NULL,
    ITEM2 CHAR(50) NULL,
    ITEM3 CHAR(50) NULL,
    ITEM4 CHAR(50) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO CLINICALTEXT (
    RECORDID,
    ITEMNAME,
    ITEMCODE,
    ITEMTYPE,
    OBJECTCODE,
    ITEM1,
    ITEM2,
    ITEM3,
    ITEM4,
    UPDATED
 )
VALUES (
    1,
   'Blood Test',
    1001,
    1,
    2001,
   'Value1',
   'Value2',
   'Value3', 
   'Value4',
   '2024-05-30 14:00:00'
); 




CREATE TABLE ContactNoteReasons (
    RecordID INT AUTO_INCREMENT NOT NULL,
    RecordStatus INT NOT NULL,
    ReasonCode INT NOT NULL,
    Reason VARCHAR(50) NOT NULL,
    AU INT NOT NULL,
    NZ INT NOT NULL,
    BHAInboxType INT NOT NULL,
    BHASystemType INT NOT NULL,
    Chargeable INT NOT NULL,
    Notification INT NOT NULL,
    ShowInbox INT NOT NULL,
    TimeToLive BIGINT NOT NULL,
    Created DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    Updated DATETIME NULL,
    UpdatedBy INT NULL,
    ActiveForManual INT NOT NULL,
    BHAInboxHeading VARCHAR(100) NULL,
    BHAMinVersion NVARCHAR(10) NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO ContactNoteReasons (
    RecordStatus,
    ReasonCode,
    Reason,
    AU,
    NZ,
    BHAInboxType,
    BHASystemType,
    Chargeable, 
    Notification,
    ShowInbox,
    TimeToLive,
    Created, 
    CreatedBy,
    Updated,
    UpdatedBy, 
    ActiveForManual,
    BHAInboxHeading,
    BHAMinVersion
 )
VALUES (
    1,
    1001,
    'Reason 1',
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    86400,
   '2024-05-30 14:00:00',
    1,
    NULL,
    NULL,
    1,
   'Heading 1',
   '1.0'
);


CREATE TABLE Country (
    RecordID INT AUTO_INCREMENT NOT NULL,
    Name VARCHAR(50) NULL,
    Abbreviation CHAR(2) NOT NULL,
    Start DATETIME NULL,
    End DATETIME NULL,
    Longname TEXT NULL,
    Status TINYINT NULL,
    Updated DATETIME NOT NULL,
    ICAOCode VARCHAR(3) NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO Country (
    Name,
    Abbreviation,
    Start,
    End,
    Longname,
    Status,
    Updated,
    ICAOCode
)
VALUES (
    'Australia',
    'AU', 
    '2024-01-01 00:00:00',
     NULL,
    'Commonwealth of Australia',
     1,
    '2024-05-30 14:00:00', 
    'AUS'
);
 


CREATE TABLE VACCINESITE (
    RECORDID INT NOT NULL,
    SITECODE CHAR(4) NOT NULL,
    SITE CHAR(100) NOT NULL,
    SNOMED CHAR(18) NOT NULL,
    AU INT NOT NULL,
    NZ INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINESITE (
    RECORDID,
    SITECODE,
    SITE,
    SNOMED,
    AU,
    NZ,
    UPDATED
 ) VALUES (
    1,
    'SC01',
   'Left Arm',
   '123456789012345678',
   1, 
   1,
  '2024-05-30 14:00:00'
);
     



CREATE TABLE ACCACTIVITIES (
    ACTIVITYCODE INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    SORTORDER INT NOT NULL,
    PRIMARY KEY (ACTIVITYCODE)
);

INSERT INTO ACCACTIVITIES (
    ACTIVITYCODE,
    RECORDSTATUS,
    DESCRIPTION,
    SORTORDER
) VALUES (
    1, 
    1,
   'Activity 1',
    10
);



#/* Table 71 *********************************/
CREATE TABLE VisitItems (
    ItemID INT NOT NULL,
    ItemName CHAR(40) NOT NULL,
    YesText CHAR(100) NULL,
    NoText CHAR(100) NULL,
    ItemType INT NOT NULL,
    ListText VARCHAR(500) NULL,
    MDType INT NULL,
    MDCode INT NULL,
    Category INT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (ItemID)
);

INSERT INTO VisitItems (
    ItemID, 
    ItemName,
    YesText,
    NoText,
    ItemType,
    ListText, 
    MDType,
    MDCode,
    Category,
    UPDATED
) VALUES (
    2,
   'Temperature', 
   'Fever',
   'Normal',
    2,
   'Temperature details', 
    102,
    202,
    2,
   '2024-05-30 14:30:00'
);



#/* Table 72 *********************************/
CREATE TABLE WARNINGCODES (
    WARNINGCODE INT NOT NULL,
    WARNINGTYPE INT NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    WARNINGSUBCODE INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (WARNINGCODE)
);

INSERT INTO WARNINGCODES (
    WARNINGCODE,
    WARNINGTYPE,
    DESCRIPTION,
    WARNINGSUBCODE,
    UPDATED
) VALUES (
    2, 
    2,
   'Moderate reaction to sulfa drugs',
    102,
   '2024-05-30 14:30:00'
);



/* Table 73 *********************************/
CREATE TABLE VACCINES (
    VACCINEID INT NOT NULL,
    VACCINENAME CHAR(50) NOT NULL,
    ACIRCODE CHAR(20) NOT NULL,
    CHILDHOOD INT NOT NULL,
    GENERIC INT NOT NULL,
    UPDATED DATETIME NULL,
    NZ INT NOT NULL,
    NIR INT NOT NULL,
    NZChildhood INT NOT NULL,
    AU INT NOT NULL,
    NZCODE CHAR(6) NULL,
    NZSHORT CHAR(100) NULL,
    NZLONG VARCHAR(500) NULL,
    NZCODESYSTEM CHAR(4) NULL,
    Funded INT NOT NULL,
    RouteRequired INT NOT NULL,
    BatchMandatory INT NOT NULL,
    PRIMARY KEY (VACCINEID)
);

INSERT INTO VACCINES (
    VACCINEID,
    VACCINENAME,
    ACIRCODE, 
    CHILDHOOD,
    GENERIC,
    UPDATED, 
    NZ,
    NIR, 
    NZChildhood,
    AU, 
    NZCODE,
    NZSHORT,
    NZLONG,
    NZCODESYSTEM,
    Funded,
    RouteRequired,
    BatchMandatory
) VALUES (
    2,
   'MMR', 
   'MMR1234567890',
    1,
    0, 
   '2024-05-30 14:30:00',
    1,
    1,
    1,
    1,
   'MMR',
   'MMR Vaccine',
   'Measles, Mumps, Rubella vaccine',
   'MMR',
    1,
    1,
    1
 );



/* Table 74 *********************************/
CREATE TABLE VACCINEINDICATION (
    RECORDID INT NOT NULL,
    INDICATIONCODE CHAR(3) NOT NULL,
    INDICATION CHAR(100) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINEINDICATION (
    RECORDID,
    INDICATIONCODE,
    INDICATION,
    UPDATED
) VALUES ( 
    2,
   'B02', 
   'HIV infection',
   '2024-05-30 14:30:00'
);



/* Table 75 *********************************/
CREATE TABLE VACCINECOMPLETION (
    RECORDID INT NOT NULL,
    COMPLETIONCODE CHAR(3) NOT NULL,
    MEANING CHAR(150) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINECOMPLETION (
    RECORDID, 
    COMPLETIONCODE,
    MEANING, 
    UPDATED
) VALUES (
    2, 
   'C02', 
   'Completed second dose', 
   '2024-05-30 14:30:00'
);



/* Table 76 *********************************/
CREATE TABLE VACCINEROUTE (
    RECORDID INT NOT NULL,
    ROUTECODE CHAR(3) NOT NULL,
    ROUTE CHAR(100) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINEROUTE (
    RECORDID,
    ROUTECODE,
    ROUTE,
    UPDATED
) VALUES (
    2, 
   'SC', 
   'Subcutaneous', 
   '2024-05-30 14:30:00'
);

/* Table 77 *********************************/
CREATE TABLE VACCINEREFUSAL (
    RECORDID INT NOT NULL,
    REFUSALCODE CHAR(3) NOT NULL,
    MEANING CHAR(100) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINEREFUSAL (
    RECORDID,
    REFUSALCODE,
    MEANING,
    UPDATED
) VALUES (
    2, 
   'R02',
   'Medical contraindications', 
   '2024-05-30 14:30:00'
);



/* Table 78 *********************************/
CREATE TABLE VACCINEACTION (
    RECORDID INT NOT NULL,
    ACTIONCODE CHAR(3) NOT NULL,
    ACTION CHAR(100) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO VACCINEACTION (
    RECORDID, 
    ACTIONCODE,
    ACTION, 
    UPDATED
) VALUES (
    2, 
   'A02',
   'Administered second dose',
   '2024-05-30 14:30:00'
);

/* Table 79 *********************************/
CREATE TABLE VACCINE_STATE (
    RecordID INT NOT NULL,
    RecordStatus INT NOT NULL,
    StateCode INT NOT NULL,
    DiseaseCode INT NOT NULL,
    Sequence INT NOT NULL,
    VaccineID INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO VACCINE_STATE (
    RecordID, 
    RecordStatus,
    StateCode, 
    DiseaseCode, 
    Sequence, 
    VaccineID, 
    UPDATED
) VALUES (
    2, 
    1, 
    102,
    202, 
    2, 
    302, 
   '2024-05-30 14:30:00'
);



#/* Table 80 *********************************/
CREATE TABLE VACCINE_DISEASE (
    VACCINEID INT NOT NULL,
    DISEASECODE INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (VACCINEID, DISEASECODE)
);

INSERT INTO VACCINE_DISEASE (
    VACCINEID, 
    DISEASECODE, 
    RECORDSTATUS, 
    UPDATED
) VALUES (
    2, 
    202, 
    1, 
   '2024-05-30 14:30:00'
);


/* Table 81 *********************************/
CREATE TABLE UPDATEREQUIRED (
    UPDATECODE INT NOT NULL,
    UPDATENAME CHAR(100) NOT NULL,
    UPDATED DATETIME NOT NULL,
    PRIMARY KEY (UPDATECODE)
);

INSERT INTO UPDATEREQUIRED (
    UPDATECODE, 
    UPDATENAME, 
    UPDATED
) VALUES (
    2, 
   'Security Patch',
   '2024-05-30 14:30:00'
);



/* Table 82 *********************************/
CREATE TABLE TYROEXCLUSIONS (
    RECORDID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    ITEM INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RECORDID)
);

INSERT INTO TYROEXCLUSIONS (
    RECORDID, 
    RECORDSTATUS,
    ITEM, 
    UPDATED
) VALUES (
    2,
    0,
    1002,
    '2024-05-30 14:30:00'
);



/* Table 83 *********************************/
CREATE TABLE TravelVaccines (
    VaccineID INT NULL,
    DiseaseID INT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME NULL,
    ProductID INT NOT NULL,
    PackID INT NOT NULL,
    DOSES INT NOT NULL,
    Booster1 INT NULL,
    Booster2 INT NULL,
    ACCDOSES INT NOT NULL,
    ACCBooster1 INT NOT NULL,
    ACCBooster2 INT NOT NULL,
    ACCBooster3 INT NOT NULL,
    PRIMARY KEY (ProductID, PackID)
);

INSERT INTO TravelVaccines (
     VaccineID,
     DiseaseID,
     RECORDSTATUS,
     UPDATED,
     ProductID,
     PackID,
     DOSES,
     Booster1,
     Booster2,
     ACCDOSES,
     ACCBooster1,
     ACCBooster2,
     ACCBooster3
)
VALUES (
     2,
     2,
     1,
    '2024-05-30 14:30:00',
     1002,
     2002,
     3, 
     9,
     15,
     3,
     9,
     15,
     21
);



/* Table 84 *********************************/
CREATE TABLE TRAVELREQUIREMENTS (
    RequirementCode INT NOT NULL,
    RequirementText CHAR(50) NOT NULL,
    DiseaseID INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RequirementCode)
);

INSERT INTO TRAVELREQUIREMENTS (
    RequirementCode, 
    RequirementText, 
    DiseaseID, 
    UPDATED
) VALUES (
     2, 
    'Yellow Fever Card', 
     2, 
   '2024-05-30 14:30:00');




/* Table 85 *********************************/
CREATE TABLE TravelRegions (
    RegionID INT NOT NULL,
    RegionName CHAR(100) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RegionID)
);

INSERT INTO TravelRegions (
    RegionID, 
    RegionName, 
    UPDATED
)
VALUES (
    2, 
   'Southeast Asia', 
   '2024-05-30 14:30:00'
);




/* Table 86 *********************************/
CREATE TABLE TRAVELNOTES (
    TRAVELNOTEID INT NOT NULL,
    NoteText VARCHAR(2000) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (TRAVELNOTEID)
);

INSERT INTO TRAVELNOTES (
    TRAVELNOTEID, 
    NoteText, 
    UPDATED)
VALUES (
     2, 
    'Important information about disease prevention.', 
    '2024-05-30 14:30:00'
);




/* Table 87 *********************************/
CREATE TABLE TravelLeaflets (
    LEAFLETID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    LEAFLETNAME CHAR(250) NULL,
    UPDATED DATETIME NOT NULL,
    PRIMARY KEY (LEAFLETID)
);

INSERT INTO TravelLeaflets (
    LEAFLETID, 
    RECORDSTATUS, 
    LEAFLETNAME, 
    UPDATED
) VALUES (
    2, 
    0, 
   'Traveler''s Diarrhea Information Leaflet', 
   '2024-05-30 14:30:00'
);




/* Table 88 *********************************/
CREATE TABLE TravelDiseases (
    DiseaseID INT NOT NULL,
    DiseaseName CHAR(50) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (DiseaseID)
);

INSERT INTO TravelDiseases (
    DiseaseID, 
    DiseaseName, 
    UPDATED
)
VALUES (
    2, 
   'Malaria', 
   '2024-05-30 14:30:00'
);




/* Table 89 *********************************/
CREATE TABLE TravelDetail (
    RecordID INT NOT NULL,
    DestinationID INT NOT NULL,
    DiseaseID INT NOT NULL,
    TravelNoteID INT NOT NULL,
    RequirementCode INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO TravelDetail (
    RecordID, 
    DestinationID,
    DiseaseID, 
    TravelNoteID,
    RequirementCode, 
    UPDATED
)
VALUES(
    2, 
    2, 
    2, 
    2, 
    2, 
   '2024-05-30 14:30:00'
);




/* Table 90 *********************************/
CREATE TABLE TRAVELDESTINATIONS (
    DESTINATIONID INT NOT NULL,
    DESTINATIONNAME CHAR(60) NOT NULL,
    RegionID INT NOT NULL,
    Comment VARCHAR(5000) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (DESTINATIONID)
);

INSERT INTO TRAVELDESTINATIONS (
    DESTINATIONID,
    DESTINATIONNAME,
    RegionID,
    Comment, 
    UPDATED
) VALUES (
    1, 
   'Kenya',
    1, 
   'Comment about Kenya', 
   '2024-05-30 14:00:00'
);



/* Table 91 *********************************/
CREATE TABLE TESTNAMES (
    TestID INT NOT NULL,
    TestName VARCHAR(1000) NULL,
    TestCode CHAR(150) NULL,
    LabID INT NOT NULL,
    Synonyms VARCHAR(1000) NULL,
    Information VARCHAR(8000) NULL,
    TestInformation VARCHAR(1000) NULL,
    Containers VARCHAR(1000) NULL,
    Transport VARCHAR(1000) NULL,
    BillingInfo VARCHAR(1000) NULL,
    PatientInfo VARCHAR(1000) NULL,
    CollectionInfo VARCHAR(1000) NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (TestID)
);

INSERT INTO TESTNAMES (
    TestID, 
    TestName, 
    TestCode, 
    LabID, 
    Synonyms, 
    Information, 
    TestInformation, 
    Containers, 
    Transport, 
    BillingInfo, 
    PatientInfo, 
    CollectionInfo, 
    UPDATED
)
VALUES (
    2, 
   'Lipid Profile', 
   'LP456', 
    102, 
   'Cholesterol Test, 
    Lipid Panel', 
   'Information about Lipid Profile', 
   'Test Info about Lipid Profile',
    'Containers for Lipid Profile', 
   'Transport for Lipid Profile', 
   'Billing Info for Lipid Profile', 
   'Patient Info for Lipid Profile', 
   'Collection Info for Lipid Profile', 
   '2024-05-30 15:30:00'
);



/* Table 92 *********************************/
CREATE TABLE TERMNAMES (
    TERMNAMEID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    TERMID INT NOT NULL,
    TERMNAME CHAR(250) NOT NULL,
    DESCRIPTION TEXT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (TERMNAMEID)
);

INSERT INTO TERMNAMES (
    TERMNAMEID, 
    RECORDSTATUS, 
    TERMID, 
    TERMNAME, 
    DESCRIPTION, 
    UPDATED
) VALUES (
    2, 
    1, 
    202, 
   'Diabetes', 
   'Chronic condition characterized by high blood sugar levels', 
   '2024-05-30 16:30:00'
);


/* Table 93 *********************************/
CREATE TABLE TERMGROUPS (
    TERMGROUPID INT NOT NULL,
    GROUPNAME CHAR(50) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (TERMGROUPID)
);

INSERT INTO TERMGROUPS (
    TERMGROUPID, 
    GROUPNAME, 
    UPDATED
) VALUES (
    2, 
   'Endocrinology', 
   '2024-05-30 17:30:00'
);

/* Table 94 *********************************/
CREATE TABLE TEMPLATES (
    TEMPLATEID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    TEMPLATENAME CHAR(50) NULL,
    SUPPLIED INT NOT NULL,
    STATE INT NOT NULL,
    CATEGORY INT NULL,
    PAGESETTINGS CHAR(50) NULL,
    CONTENT TEXT NULL,
    UPDATED DATETIME NULL,
    BINARYCONTENT LONGBLOB NULL,
    PRIMARY KEY (TEMPLATEID)
);

INSERT INTO TEMPLATES (
    TEMPLATEID, 
    RECORDSTATUS, 
    TEMPLATENAME, 
    SUPPLIED, 
    STATE, 
    CATEGORY,
    PAGESETTINGS, 
    CONTENT, 
    UPDATED, 
    BINARYCONTENT
)
VALUES(
    2, 
    1, 
   'Prescription', 
    1, 
    1, 
    102, 
    'A5', 
    'Content of prescription template', 
    '2024-05-30 18:30:00', 
     NULL
);


/* Table 95 *********************************/
CREATE TABLE TERM_TERMGROUPS (
    TERMGROUPID INT NOT NULL,
    TERMID INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (TERMGROUPID, TERMID)
);

INSERT INTO TERM_TERMGROUPS (
    TERMGROUPID, 
    TERMID, 
    RECORDSTATUS,
    UPDATED
) VALUES (
    2, 
    202, 
    1, 
   '2024-05-30 19:30:00'
);


/* Table 96 *********************************/
CREATE TABLE TELEHEALTH (
    RecordID INT NOT NULL,
    RecordStatus INT NOT NULL,
    MBSItem INT NOT NULL,
    UPDATED DATETIME NOT NULL,
    PRIMARY KEY (RecordID)
);

INSERT INTO TELEHEALTH (
    RecordID, 
    RecordStatus, 
    MBSItem, 
    UPDATED
)
VALUES(
    2,
    1, 
    302, 
   '2024-05-30 20:30:00'
);



/* Table 97 *********************************/
CREATE TABLE STATES (
    STATECODE INT NOT NULL,
    LONGNAME CHAR(30) NULL,
    SHORTNAME CHAR(3) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (STATECODE)
);

INSERT INTO STATES (
     STATECODE,  
     LONGNAME, 
     SHORTNAME, 
     UPDATED
)
VALUES(
     2, 
    'New York', 
    'NY', 
    '2024-05-30 21:30:00');



/* Table 98 *********************************/
CREATE TABLE SERVICEURL (
    ServiceCode INT NOT NULL,
    ServiceType INT NOT NULL,
    Description VARCHAR(255) NULL,
    URL VARCHAR(255) NULL,
    TESTURL VARCHAR(255) NULL,
    ApplicationID VARCHAR(255) NULL,
    Created DATETIME NOT NULL,
    Updated DATETIME NULL,
    ServiceUser VARCHAR(255) NULL,
    Password VARCHAR(255) NULL,
    PRIMARY KEY (ServiceCode)
);

INSERT INTO SERVICEURL (
    ServiceCode, 
    ServiceType, 
    Description, 
    URL, 
    TESTURL, 
    ApplicationID, 
    Created, 
    Updated, 
    ServiceUser, 
    Password
)
VALUES (
    2, 
    2, 
   'Backup Service', 
   'https://backup.service.url', 
   'https://test.backup.url', 
   'AppID002', 
   '2024-05-30 22:30:00', 
   '2024-05-30 23:30:00', 
   'user002', 
   'password002'
);


/* Table 99 *********************************/
CREATE TABLE ROUTES (
    ROUTEID INT NOT NULL,
    ROUTENAME VARCHAR(25) NOT NULL,
    TGACODE CHAR(6) NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (ROUTEID)
);

INSERT INTO ROUTES (
    ROUTEID, 
    ROUTENAME, 
    TGACODE, 
    UPDATED
) VALUES (
     2, 
     'Intravenous',
     'IV456', 
    '2024-05-30 23:30:00'
);


/* Table 100 *********************************/
CREATE TABLE SCHEDULE (
    PRODUCTID INT NOT NULL,
    PACKID INT NOT NULL,
    STATE INT NOT NULL,
    SCHEDULE INT NOT NULL,
    RECORDSTATUS INT NOT NULL,
    UPDATED DATETIME NULL,
    PRIMARY KEY (PRODUCTID, PACKID, STATE, SCHEDULE)
);

INSERT INTO SCHEDULE (
    PRODUCTID,
    PACKID, 
    STATE, 
    SCHEDULE, 
    RECORDSTATUS, 
    UPDATED
)
VALUES (
    2, 
    102, 
    2, 
    2, 
    1, 
   '2024-05-30 23:50:00');





/****************************************/ 

 

CREATE VIEW Appointment_Product_Info AS

SELECT 
    A.RECORDID AS Appointment_RecordID,
    A.INTERNALID AS Patient_InternalID,
    A.APPOINTMENTDATE AS Appointment_Date,
    A.APPOINTMENTTIME AS Appointment_Time,
    A.APPOINTMENTLENGTH AS Appointment_Length,
    A.REASON AS Appointment_Reason,
    PI.PRODUCTID AS Product_ID,
    PR.STRENGTH AS Product_Strength,
    PR.PRODUCTDESCRIPTION AS Product_Description,
    I.DESCRIPTION AS Interaction_Description
FROM 
    APPOINTMENTS A
LEFT JOIN 
    PRODUCTINTERACTIONS PI ON A.RECORDID = PI.RECORDID
LEFT JOIN 
    PRODUCTS PR ON PI.PRODUCTID = PR.PRODUCTID
LEFT JOIN 
    INTERACTIONS I ON PI.INTERACTIONID = I.INTERACTIONID;
alcoholusers

